import re

path = 'src/cargoless/schedule.rs'

replacements = [
    ("""//! `cargoless/schedule.rs` -- 拓扑排序 + 指纹 + 每 crate rustc 参数计算""", """//! `cargoless/schedule.rs` -- topological sort + fingerprint + per-crate rustc argument computation"""),
    ("""//! （D15 P2 切①/②/③，设计档 §3.6）。""", """//! (D15 P2 cut①/②/③, design doc §3.6)."""),
    ("""//! 产物布局：`cache_dir()/target/cargoless/<MIRVM_HOST>/debug/{deps,host-deps,build}`""", """//! Artifact layout: `cache_dir()/target/cargoless/<MIRVM_HOST>/debug/{deps,host-deps,build}`"""),
    ("""//! --target 产物（deps）与 host 产物（host-deps：proc-macro 闭包与 build-deps""", """//! -- target artifacts (deps) and host artifacts (host-deps: proc-macro closure and build-deps"""),
    ("""//! 闭包，真 rustc 真 codegen）分目录，同名 fp 不撞；build/ 是 build script""", """//! closure, real rustc real codegen) in separate directories, same-name fingerprints don't collide; build/ is the build-script"""),
    ("""//! 族（`build/<pkg>-<fp>/{build_script_build-<fp>,out}`，切③）；与 cargo""", """//! family (`build/<pkg>-<fp>/{build_script_build-<fp>,out}`, cut③); coexists with the cargo"""),
    ("""//! 路径的 `target/mirvm` 双轨并存（P2→P4 迁移期两条路径互不踩产物）。""", """//! path's `target/mirvm` as dual tracks (P2→P4 migration: the two paths don't trample each other's artifacts)."""),
    ("""//! 产物命名 `lib<lib_name>-<fp>.{rmeta,rlib,so}`：fp 是本文件的自定方案（cargo 的""", """//! Artifact name `lib<lib_name>-<fp>.{rmeta,rlib,so}`: fp is this file's custom scheme (cargo's"""),
    ("""//! -C metadata 算法不稳定不追，设计档 §3.6--cargo 已退场，内部一致即可）。""", """//! -C metadata algorithm is unstable and not chased, design doc §3.6--cargo has exited, internal consistency suffices)."""),
    ("""/// 产物布局（见文件头）。""", """/// Artifact layout (see file header)."""),
    ("""    /// target 产物目录（__cless-dep，-Zno-codegen rlib）。""", """    /// Target artifact directory (__cless-dep, -Zno-codegen rlib)."""),
    ("""    /// host 产物目录（proc-macro 闭包与 build-deps 闭包，真 rustc 真 codegen）。""", """    /// Host artifact directory (proc-macro closure and build-deps closure, real rustc real codegen)."""),
    ("""    /// build script 族根目录（`build/<pkg>-<fp>/{build_script_build-<fp>,out}`）。""", """    /// Build-script family root directory (`build/<pkg>-<fp>/{build_script_build-<fp>,out}`)."""),
    ("""    /// 显式布局（D15 P4 切⑥a，sysroot 自管）：deps 指 sysroot lib 平铺目，""", """    /// Explicit layout (D15 P4 cut⑥a, sysroot self-managed): deps points to the sysroot lib flat directory,"""),
    ("""    /// host 产物与 build script 族指独立 staging（不进 sysroot lib--""", """    /// host artifacts and build-script family point to independent staging (not entering sysroot lib--"""),
    ("""    /// host 二进制与 host rlib 不是 target 产物）。""", """    /// host binaries and host rlibs are not target artifacts)."""),
    ("""    /// 一个包的 build script 工作目录（编译产物与 OUT_DIR 都在其下）。""", """    /// A package's build-script working directory (build artifacts and OUT_DIR are under it)."""),
    ("""/// 依赖图结构：正向 indegree + 反向边表（dep → 依赖者；依赖者按下标升序""", """/// Dependency graph structure: forward indegree + reverse edge table (dep → dependents; dependents enqueued in ascending index order"""),
    ("""/// 入列--构造循环按 unit 下标 0..n 逐边推入）。topo_order 与并行调度""", """/// -- construction loop pushes edges one by one over unit indices 0..n). topo_order and parallel scheduling"""),
    ("""/// （run_scheduler，D15 P3 切⑤c）共用同一构造纪律：同 unit 的多条边""", """/// (run_scheduler, D15 P3 cut⑤c) share the same construction discipline: multiple edges of the same unit"""),
    ("""/// （不同 key/class）两侧都重复计，递减次数才配平。""", """/// (different key/class) are counted repeatedly on both sides, and only decrementing the count balances."""),
    ("""    let mut dependents: Vec<Vec<usize>> = vec![Vec::new(); n]; // 反向边：dep → 依赖者""", """    let mut dependents: Vec<Vec<usize>> = vec![Vec::new(); n]; // reverse edges: dep → dependents"""),
    ("""/// Kahn 拓扑序：依赖先于依赖者。返回 units 下标序。""", """/// Kahn topological order: dependencies before dependents. Returns unit index order."""),
    ("""        return Err("内部不一致：编译单元依赖图有环（cargo 解析图本应为 DAG）".into());""", """        return Err("Internal inconsistency: compilation-unit dependency graph has a cycle (cargo resolve should be a DAG)".into());"""),
    ("""/// Kahn 就绪队列并行调度器（D15 P3 切⑤c）：unit 的全部依赖「完成」即""", """/// Kahn ready-queue parallel scheduler (D15 P3 cut⑤c): a unit is ready once all its dependencies are "done"."""),
    ("""/// 就绪；主线程跑调度循环（独占 indegree/就绪队列/完成表 state），`jobs`""", """/// The main thread runs the scheduling loop (exclusively owning indegree/ready queue/completion table state), `jobs`"""),
    ("""/// 个 worker 线程从通道领 `(下标, M)` 跑 `work`，经通道回传""", """/// worker threads receive `(index, M)` from the channel and run `work`, sending back"""),
    ("""/// `(下标, Result<T, String>)`；主线程收完成 → `on_done` 吸收 → 依赖者""", """/// `(index, Result<T, String>)` through the channel; the main thread receives completions → `on_done` absorbs → dependents'"""),
    ("""/// indegree 递减 → 新就绪入队。失败：记**第一枚**错误（按完成到达先后，""", """/// indegree decremented → newly ready enqueued. On failure: record the **first** error (by completion arrival order,"""),
    ("""/// 非 topo 位次）、停发新活、等在飞 worker 全部汇合后返回 Err。""", """/// not topo position), stop issuing new work, wait for all in-flight workers to rendezvous, then return Err."""),
    ("""/// - `build_msg(&state, ix) -> M` 与 `on_done(&mut state, ix, T)` 只在主""", """/// - `build_msg(&state, ix) -> M` and `on_done(&mut state, ix, T)` run only on the main"""),
    ("""///   线程跑--完成表（state）不跨线程，零锁；worker 开工所需的依赖侧""", """///   thread--the completion table (state) doesn't cross threads, zero locks; dependency-side inputs needed by a worker"""),
    ("""///   输入由主线程在**派发时**算好捎进 M（此刻全部依赖必已完成，取值与""", """///   are computed by the main thread at **dispatch** and carried into M (all dependencies must be done at this point, values equal"""),
    ("""///   串行版在 unit 开头算的相等）。""", """///   to those computed at unit start in the serial version)."""),
    ("""/// - `work` 在 worker 线程跑，须 `Sync`（多 worker 共享同一份闭包与其""", """/// - `work` runs on worker threads and must be `Sync` (multiple workers share the same closure and its"""),
    ("""///   捕获的只读上下文）。worker 恐慌经 catch_unwind 转成普通失败回传--""", """///   captured read-only context). Worker panics are caught via catch_unwind and converted to normal failures and sent back--"""),
    ("""///   --否则主线程会把恐慌中的 unit 记在 in_flight 里干等（恐慌 hook 照""", """///   --otherwise the main thread would keep the panicking unit in in_flight waiting (the panic hook still"""),
    ("""///   常向 stderr 打 panic 原文；与旧串行「恐慌即崩」文案有别，但那是""", """///   prints the raw panic to stderr; wording differs from the old serial "panic means crash", but that's"""),
    ("""///   内部错误路径，非对拍面）。""", """///   an internal error path, not the comparison surface)."""),
    ("""/// - jobs=1 时派发序与 topo_order 逐位一致（同 dep_graph 构造纪律 +""", """/// - With jobs=1 dispatch order matches topo_order exactly (same dep_graph construction discipline +"""),
    ("""///   单在飞 ⇒ 完成序 = 派发序 = Kahn FIFO）--对拍调试锚，钉。""", """///   single in-flight ⇒ completion order = dispatch order = Kahn FIFO)--comparison debug anchor, pinned."""),
    ("""/// 成功返回 `Ok(state)`（完成表物归原主）；`Err` = 第一枚错误原文。""", """/// On success returns `Ok(state)` (completion table returned to owner); `Err` = raw text of first error."""),
    ("""/// `indeg` 就地递减消耗（dep_graph 的产物，调用方不再复用）。""", """/// `indeg` is decremented in place and consumed (a product of dep_graph, caller no longer reuses)."""),
    ("""    // 就绪队列播种与 topo_order 同纪律：下标升序扫 indeg==0""", """    // Seed ready queue with same discipline as topo_order: scan indeg==0 in ascending index order"""),
    ("""    // std 的 mpsc 是单消费者：worker 组共享一把锁轮询领活（锁内仅一次""", """    // std's mpsc is single-consumer: worker group shares one lock to poll for jobs (only one"""),
    ("""    // recv；竞争开销相对一次 rustc 编译可忽略）""", """    // recv inside the lock; contention overhead negligible compared to one rustc compile)"""),
    ("""                            Err(_) => break, // 锁中毒（同行恐慌）= 收工""", """                            Err(_) => break, // lock poisoned (peer panic) = shutdown"""),
    ("""                        Err(_) => break, // 主端挂线 = 收工""", """                        Err(_) => break, // main end hung up = shutdown"""),
    ("""                            Err(format!("unit {ix} 的编译 worker 恐慌（内部错误）"))""", """                            Err(format!("compilation worker for unit {ix} panicked (internal error)"))"""),
    ("""                        break; // 主端已走（按计数收满才走，理论不到）--防御""", """                        break; // main end already left (should only leave after all counted, theoretically unreachable) -- defensive"""),
    ("""        let mut workers_dead = false; // 完成侧断流 = worker 全灭（锁中毒）""", """        let mut workers_dead = false; // completion side disconnected = all workers dead (lock poisoned)"""),
    ("""            // 先发活：就绪非空、在飞未满、无失败（失败即停发新活）""", """            // Issue jobs first: ready non-empty, in-flight not full, no failure (failure stops new dispatches)"""),
    ("""        drop(work_tx); // 挂线：空闲 worker 收工（scope 尾自动汇合）""", """        drop(work_tx); // hang up: idle workers shutdown (automatically rendezvous at end of scope)"""),
    ("""                "编译 worker 线程异常终止（内部错误）".to_string()""", """                "compilation worker thread terminated abnormally (internal error)".to_string()"""),
    ("""                // 活发不出也收不齐 = 依赖图有环（正常路径到不了：""", """                // Can't issue all jobs and can't collect all completions = dependency graph has a cycle (normal path can't reach:"""),
    ("""                // fingerprints 内的 topo_order 会先炸）--兜底响亮""", """                // topo_order inside fingerprints would fail first) -- loud fallback"""),
    ("""                "内部不一致：编译单元依赖图有环（cargo 解析图本应为 DAG）".to_string()""", """                "Internal inconsistency: compilation-unit dependency graph has a cycle (cargo resolve should be a DAG)".to_string()"""),
    ("""/// host 闭包（切②）：从每个 proc-macro unit 沿 dep 边 BFS 的可达集（含""", """/// Host closure (cut②): reachable set via BFS along dep edges from each proc-macro unit (including"""),
    ("""/// proc-macro 自身）。边不分类跟随--proc-macro 的 Build 边（它的""", """/// the proc-macro itself). Edges are followed regardless of class--proc-macro Build edges (its"""),
    ("""/// build-deps）同样是 host 编译输入。闭包单元用真 rustc 真 codegen 编成""", """/// build-deps) are also host compile inputs. Closure units are compiled with real rustc real codegen into"""),
    ("""/// host 产物。""", """/// host artifacts."""),
    ("""/// 根包本身是 proc-macro 时，它的 Normal 依赖也是宿主编译输入；依赖""", """/// When the root package itself is a proc-macro, its Normal dependencies are also host compile inputs; beyond"""),
    ("""/// proc-macro 的闭包之外，再从根 Normal 边沿全依赖边扩张。""", """/// the proc-macro closure, expand along all dependency edges from root Normal edges."""),
    ("""/// build-deps 闭包（切③）：种子 = 每个 has_build_script unit 的 **Build 类""", """/// Build-deps closure (cut③): seeds = **Build-class** edges of every has_build_script unit"""),
    ("""/// 边**（root_has_build 时根的 Build 边也算--根不是 unit，driver 传""", """/// (root's Build edges also count when root_has_build--root is not a unit, driver passes"""),
    ("""/// manifest.has_build_script）；闭包内沿**全部**边扩张（build-dep 的普通""", """/// manifest.has_build_script); inside the closure expand along **all** edges (a build-dep's normal"""),
    ("""/// 依赖同样是 host 编译输入；build-dep 自己也可以有 build.rs，其""", """/// dependencies are also host compile inputs; a build-dep itself may also have build.rs, its"""),
    ("""/// build-deps 随全边扩张自然入闭包，topo 序保证它先跑）。闭包单元用真""", """/// build-deps naturally enter the closure by expanding all edges, topo order ensures they run first). Closure units are compiled with real"""),
    ("""/// rustc 真 codegen 编成 host 产物（host-deps 目录）。""", """/// rustc real codegen into host artifacts (host-deps directory)."""),
    ("""/// target 编译集（切②③）：从根的 Normal 类边出发沿 Normal 边 BFS--""", """/// Target compile set (cut②③): BFS along Normal edges starting from root's Normal-class edges--"""),
    ("""/// Build 边不是代码依赖（切①② 靠 strip_build_units 掩盖，切③ 修正面）；""", """/// Build edges are not code dependencies (cut①② masked by strip_build_units, cut③ correction side);"""),
    ("""/// proc-macro unit 对 target 是叶子--不进集、也不钻入其内部（它的依赖是""", """/// proc-macro unit is a leaf for target--not entered into the set, nor drilled into its internals (its deps are"""),
    ("""/// host 依赖，不是根的 target 依赖；cargo 也不为 proc-macro crate 产""", """/// host deps, not the root's target deps; cargo also doesn't produce a target rlib for a proc-macro crate"""),
    ("""/// target rlib）。与 host 闭包可相交：同一 unit 同时被 bin 与 proc-macro""", """/// target rlib). It may intersect with the host closure: a unit used by both bin and proc-macro"""),
    ("""/// 用时两侧都编，双份产物分目录互不影响。""", """/// is compiled on both sides; the two copies in separate directories don't affect each other."""),
    ("""/// 每 unit 的内容指纹（按 topo 序算--dep 的 fp 先于依赖者产出）。""", """/// Per-unit content fingerprint (computed in topo order--dep fp produced before the dependent)."""),
    ("""/// fp(unit) = fnv1a(BUILD_ID, package, version, edition, 排序后 features,""", """/// fp(unit) = fnv1a(BUILD_ID, package, version, edition, sorted features,"""),
    ("""/// profile 三员, sysroot_stamp, rustflags 逐条, 源 stamp, **排序后各 dep 的 fp**)。""", """/// profile trio, sysroot_stamp, rustflags one by one, source stamp, **sorted fp of each dep**)."""),
    ("""/// 最后这枚必须含：depsimage pre-key 的「传递闭包变更 ⇒ 直接依赖产物盖戳变」""", """/// This last one must include: the depsimage pre-key invariant "transitive closure change ⇒ direct dependency artifact fingerprint changes""""),
    ("""/// 不变量靠它传播--传递 dep 的 fp 变 ⇒ 直接 dep 的 fp 变 ⇒ 其产物文件名变""", """/// is propagated through it--transitive dep fp change ⇒ direct dep fp change ⇒ its artifact filename changes"""),
    ("""/// ⇒ bin 的 --extern 盖戳变（depsimage.rs 头注同款语义；钉死，勿删）。""", """/// ⇒ bin's --extern fingerprint changes (same semantics as depsimage.rs header note; pinned, do not delete)."""),
    ("""/// 无 dep 源变化但 lock 版本集变化时，版本字段已覆盖。""", """/// When no dep source changes but the lock version set changes, the version field already covers it."""),
    ("""/// rustflags（D15 P3 切⑤a）逐条按序进全部 unit fp：host 侧不吃 rustflags""", """/// rustflags (D15 P3 cut⑤a) enter every unit fp in order: host side doesn't consume rustflags"""),
    ("""/// 但跟随失效无害（v1 从简，边界记档）；顺序有语义（后旗压前旗）不排序。""", """/// but following invalidation is harmless (v1 simplified, boundary documented); order has semantics (later flag overrides earlier) so not sorted."""),
    ("""            .map(|d| fps[d.unit].clone().expect("topo 序保证 dep fp 先算"))""", """            .map(|d| fps[d.unit].clone().expect("topo order guarantees dep fp is computed first"))"""),
    ("""            put(f); // BTreeSet 迭代即字典序""", """            put(f); // BTreeSet iteration is lexicographic order"""),
    ("""            put(f); // 按序：rustflags 顺序有语义（后旗压前旗）""", """            put(f); // In order: rustflags order has semantics (later flag overrides earlier)"""),
    ("""    Ok(fps.into_iter().map(|f| f.expect("全序已填")).collect())""", """    Ok(fps.into_iter().map(|f| f.expect("total order filled")).collect())"""),
    ("""/// 源 stamp：Git 单元 = lock 中的精确 source id（含 commit）；registry 单元 =""", """/// Source stamp: Git unit = exact source id in lock (including commit); registry unit ="""),
    ("""/// 字面 "registry"（源按 cksum 不可变不盖戳--.crate 解包树的 mtime 是解包""", """/// literal "registry" (source is immutable by checksum, no fingerprint--.crate unpack tree mtime is the unpack"""),
    ("""/// 时刻，盖了只会制造无谓重建；版本号已覆盖内容）；""", """/// time, fingerprinting would only cause spurious rebuilds; version already covers content);"""),
    ("""/// path 单元 = 递归遍历 source_dir（排除 target/ 与 .git/）全部文件的""", """/// path unit = recursively traverse source_dir (excluding target/ and .git/) and fold all files'"""),
    ("""/// (相对路径, len, mtime_ns) 排序后折叠。根包同规则（root_fingerprint 复用）。""", """/// (relative path, len, mtime_ns) after sorting. Same rule for root package (reused by root_fingerprint)."""),
    ("""/// pub(super)：buildrs.rs 的 build.rs 重跑判定（D15 P3 切⑤b）default 面""", """/// pub(super): build.rs rerun decision for buildrs.rs (D15 P3 cut⑤b) default facet"""),
    ("""/// 树快照复用同一折叠--存档快照与指纹盖戳同口径，漂移同源。""", """/// tree snapshot reuses the same fold--archived snapshot and fingerprint stamp use the same measure, drift from the same source."""),
    ("""                "path 依赖 {} 源目录读取失败 {}: {e}"""", """                "path dep {} source dir read failed {}: {e}"""),
    ("""            let ent = ent.map_err(|e| format!("path 依赖 {} 源目录条目读取失败: {e}", package))?;""", """            let ent = ent.map_err(|e| format!("path dep {} source dir entry read failed: {e}", package))?;"""),
    ("""                        "path 依赖 {} 源文件 stat 失败 {}: {e}"""", """                        "path dep {} source file stat failed {}: {e}"""),
    ("""/// 根包指纹（切③：根 build script 编译缓存键 + build 目录名；切⑤a 起兼作""", """/// Root package fingerprint (cut③: root build script compile cache key + build dir name; from cut⑤a also"""),
    ("""/// 根 lib target 的产物名盖戳）。根不是 unit 不在 fingerprints() 里，同配方""", """/// root lib target artifact name fingerprint). Root is not a unit and not in fingerprints(), same recipe"""),
    ("""/// 单独算：BUILD_ID、包名/版本/edition、排序后 root features、profile 三员、""", """/// computed separately: BUILD_ID, package name/version/edition, sorted root features, profile trio,"""),
    ("""/// sysroot_stamp、rustflags 逐条（根 lib 是 target 单元吃 rustflags，fp 必""", """/// sysroot_stamp, rustflags one by one (root lib is a target unit consuming rustflags, fp must"""),
    ("""/// 含；根 build script 编译不吃、跟随失效无害）、根源 stamp、排序后全部根""", """/// include them; root build script compile doesn't consume them, following invalidation harmless), root source stamp, sorted fp of all"""),
    ("""/// 边 dep 的 fp（Build 边在--build script 的 --extern 盖戳随它们变）。""", """/// root-edge deps (Build edges included--build script's --extern fingerprint changes with them)."""),
    ("""        put(f); // 按序（unit fp 同款纪律）""", """        put(f); // In order (same discipline as unit fp)"""),
    ("""/// profile 三旗（cargo dev profile 语义钉，设计档 §6 的 jiff 判例：""", """/// Profile three flags (cargo dev profile semantics pinned, design doc §6 jiff precedent:"""),
    ("""/// debug-assertions/overflow-checks 进 MIR 语义，错配 = 对拍漂移）。""", """/// debug-assertions/overflow-checks enter MIR semantics, mismatch = comparison drift)."""),
    ("""/// 真 rustc 绝对路径：编译期烘焙的默认 sysroot 自带（manifest.rs""", """/// Real rustc absolute path: default sysroot baked in at compile time (manifest.rs"""),
    ("""/// host_cfg_atoms 同款取法）。host 侧编译只信它--PATH 上的 rustc 可能是""", """/// host_cfg_atoms same retrieval). Host-side compile only trusts it--rustc on PATH could be"""),
    ("""/// 别的工具链；proc-macro dylib 与解释会话的编译器版本必须严格一致""", """/// a different toolchain; proc-macro dylib and interpreter session compiler versions must strictly match"""),
    ("""/// （cargo_shim.rs wrapper 段同款纪律）。""", """/// (same discipline as cargo_shim.rs wrapper section)."""),
    ("""/// 一条 dep 边的 --extern 目标路径分派：dep 是 proc-macro → host-deps 的""", """/// --extern target path dispatch for one dep edge: dep is proc-macro → host-deps"""),
    ("""/// dylib（消费方编译期 dlopen 展开宏）；否则指本侧目录的 ext 产物。""", """/// dylib (consumer compile-time dlopen expands macros); otherwise points to ext artifact in this side's directory."""),
    ("""/// 本包 BuildOutput 的编译旗追加（E1 实证：-l/cfg/check-cfg/link-arg 只进""", """/// Append this package's BuildOutput compile flags (E1 empirical: -l/cfg/check-cfg/link-arg only enter"""),
    ("""/// 本包；-L 本包 + 传递汇集 `searches`）。rustc-env 不进 argv--经 driver""", """/// this package; -L this package + transitive collected `searches`). rustc-env is not in argv--via driver's"""),
    ("""/// 的 cmd.env 注入（连同 OUT_DIR）。旗序对齐 cargo 本包行（-L、-l、""", """/// cmd.env injection (together with OUT_DIR). Flag order aligns with cargo's per-package line (-L, -l,"""),
    ("""/// link-arg、--cfg、--check-cfg），对拍不比对 argv 但保持形态诚实。""", """/// link-arg, --cfg, --check-cfg), comparison doesn't compare argv but keeps shape honest."""),
    ("""/// 一个 dep unit 的 rustc 参数（driver 起 `__cless-dep` 子进程喂""", """/// rustc args for one dep unit (driver spawns `__cless-dep` child fed to"""),
    ("""/// cli::run_dep_compiler；形态对齐 cargo 对 target 依赖的调用 +""", """/// cli::run_dep_compiler; shape aligns with cargo's target-dependency invocation +"""),
    ("""/// cargo_shim.rs wrapper 段的 MIR sysroot/-Z 注入）。""", """/// MIR sysroot/-Z injection from cargo_shim.rs wrapper section)."""),
    ("""/// argv0 = "mirvm-cless-rustc"（driver 起子进程时剥掉补真名）。""", """/// argv0 = "mirvm-cless-rustc" (driver strips and fills real name when spawning child)."""),
    ("""/// extern 只吃 **Normal 类边**（Build 边不是代码依赖--切③ 修正面）；""", """/// extern only consumes **Normal-class edges** (Build edges are not code dependencies--cut③ correction side);"""),
    ("""/// `bo` = 本 unit 的 build script 产物，`searches` = 传递 -L 汇集。""", """/// `bo` = this unit's build script output, `searches` = transitive -L collection."""),
    ("""/// `rustflags`（D15 P3 切⑤a）追加在参数串**末尾**（-Z 旗之后）：rustc""", """/// `rustflags` (D15 P3 cut⑤a) appended at **end** of arg list (after -Z flags): rustc"""),
    ("""/// 后旗压前旗，用户旗覆盖先行旗--实证见 rustflags.rs 头注（有 --target""", """/// later flag overrides earlier, user flags override preceding flags--empirical evidence in rustflags.rs header note (with --target"""),
    ("""/// 时 rustflags 只落 target 单元；host 侧参数函数签名不含 rustflags）。""", """/// rustflags only land on target units; host-side arg function signatures don't include rustflags)."""),
    ("""// 平铺参数 = 编译配方各槽一一对应（manifest.rs pkg_env_map 同款先例）；""", """// Flat args = compile recipe slots one-to-one (same precedent as manifest.rs pkg_env_map);"""),
    ("""// 包成 struct 反而失去与 argv 段的目视对应""", """// Packing into a struct loses visual correspondence with argv segments"""),
    ("""        // registry 代码不归用户改，lint 全哑（cargo 同）；path 依赖照常告警""", """        // Registry code isn't user-modified, lints silenced (same as cargo); path deps warn as usual"""),
    ("""    // extra-filename 必须作为 -C 的下一个独立 argv 槽--run_dep_compiler 按""", """    // extra-filename must be the next independent argv slot after -C--run_dep_compiler extracts"""),
    ("""    // 窗口（两个独立槽）抠它定 rlib 主名""", """    // it via a window (two independent slots) to set the rlib main name"""),
    ("""    // host-deps 也进 -L：经 facade 再导出的 proc-macro（serde → serde_derive""", """    // host-deps also goes into -L: proc-macro re-exported through facade (serde → serde_derive"""),
    ("""    // 实锤）被 rustc 按 crate hash 在 -L 目里找 .so--cargo 单 deps 目天然""", """    // confirmed) is looked up by rustc in -L directories by crate hash--cargo's single deps dir naturally"""),
    ("""    // 覆盖，我们双目必须都列""", """    // covers it, our two directories must both be listed"""),
    ("""            continue; // Build 边不是代码依赖（切③ 修正面）""", """            continue; // Build edges are not code dependencies (cut③ correction side)"""),
    ("""        // proc-macro 边指 host-deps 的 dylib；普通边照旧 target .rmeta""", """        // proc-macro edge points to host-deps dylib; normal edge remains target .rmeta"""),
    ("""    // rustflags 末尾追加：后旗压前旗（--cap-lints allow 须压住 path 依赖的""", """    // rustflags appended at end: later flag overrides earlier (--cap-lints allow must override path dep's"""),
    ("""    // 内置 lint 行为）""", """    // built-in lint behavior)"""),
    ("""/// bin（根 crate）会话参数--走既有 MirvmCallbacks 降低通道（after_analysis""", """/// bin (root crate) session args--uses the existing MirvmCallbacks lowering pipeline (after_analysis"""),
    ("""/// 停，Compilation::Stop，零产物）：**不**加 -Z 旗、--out-dir、-C metadata""", """/// stop, Compilation::Stop, zero artifacts): **do not** add -Z flags, --out-dir, -C metadata"""),
    ("""/// （与 cargo 路径 runner 段的 bin 会话同形态）。""", """/// (same shape as cargo-path runner bin session)."""),
    ("""/// extern 只吃 Normal 类根边；`bo` = 根 build script 产物（cfg/check-cfg/""", """/// extern only consumes Normal-class root edges; `bo` = root build script output (cfg/check-cfg/"""),
    ("""/// link 旗进会话），`searches` = 传递 -L 汇集。""", """/// link flags enter session), `searches` = transitive -L collection."""),
    ("""/// `rustflags`（D15 P3 切⑤a）追加在参数串**末尾**（--sysroot 之后）：""", """/// `rustflags` (D15 P3 cut⑤a) appended at **end** of arg list (after --sysroot):"""),
    ("""/// 后旗压前旗（bin 是 path 包无内置 --cap-lints，RUSTFLAGS 的 --cap-lints""", """/// later flag overrides earlier (bin is a path package with no built-in --cap-lints, RUSTFLAGS' --cap-lints"""),
    ("""/// allow 在此压住 lint 告警--hexyl/tokei 对拍场景）。""", """/// allow suppresses lint warnings here--hexyl/tokei comparison scenarios)."""),
    ("""/// `root_lib` = Some((lib_name, lib_fp)) 时补根包 lib target 的 --extern""", """/// When `root_lib` = Some((lib_name, lib_fp)) add root package lib target --extern"""),
    ("""/// （[lib]+[[bin]] 双 target 时 bin 隐式依赖同名 lib--hexyl 实锤，cargo""", """/// (when [lib]+[[bin]] dual targets, bin implicitly depends on same-name lib--hexyl confirmed, cargo"""),
    ("""/// 实证行里根 lib 与其余 --extern 混排指 .rlib；root_lib_rustc_args 的产物）。""", """/// empirical line mixes root lib with other --extern pointing to .rlib; output of root_lib_rustc_args)."""),
    ("""// 平铺参数先例同 dep_rustc_args""", """// Flat-args precedent same as dep_rustc_args"""),
    ("""    // file!()/panic Location/诊断路径 parity（redb_kv 的 Location Display 与""", """    // file!()/panic Location/diagnostic path parity (redb_kv Location Display and"""),
    ("""    // gix_pure 的 panic 位置实锤）：cargo 以 cwd=包根 + 相对路径 src/main.rs""", """    // gix_pure panic location confirmed): cargo invokes rustc with cwd=package root + relative path src/main.rs"""),
    ("""    // 调 rustc，本地包路径在一切输出里都是相对形；我们传绝对路径，用 remap""", """    // , local package paths are relative in all output; we pass absolute paths and use remap"""),
    ("""    // 把 Cargo 编译根（workspace 根；单包时等于包根）前缀重写为空--rustc book：remap 影响 all output including""", """    // to rewrite the Cargo compile root (workspace root; equals package root for a single package) prefix to empty--rustc book: remap affects all output including"""),
    ("""    // compiler diagnostics（真 rustc 实证：绝对输入 + remap 的 file!() 与""", """    // compiler diagnostics (real rustc evidence: absolute input + remap file!()"""),
    ("""    // 相对输入逐字节同）。registry/path 依赖路径仍绝对（cargo 同），只盖""", """    // byte-identical to relative input). registry/path dep paths remain absolute (same as cargo), only cover"""),
    ("""    // 根包目录。""", """    // root package directory."""),
    ("""            continue; // Build 边不是代码依赖（切③ 修正面）""", """            continue; // Build edges are not code dependencies (cut③ correction side)"""),
    ("""        // bin 侧 --extern 用 .rlib（对齐 cargo 的最终 crate 调用形态）；""", """        // bin-side --extern uses .rlib (aligns with cargo's final crate invocation shape);"""),
    ("""        // proc-macro 根边指 host-deps 的 dylib""", """        // proc-macro root edge points to host-deps dylib"""),
    ("""    // 根包 lib target 的 --extern。同包根是 proc-macro 时指宿主动态库；""", """    // root package lib target --extern. When the same root is proc-macro it points to host dynamic lib;"""),
    ("""    // 普通 lib 仍指 target rlib。""", """    // normal lib still points to target rlib."""),
    ("""    // host-deps 也进 -L（facade 再导出 proc-macro 的 .so 查找--serde →""", """    // host-deps also goes into -L (lookup for facade re-exported proc-macro .so--serde →"""),
    ("""    // serde_derive 实锤；dep_rustc_args 同款注释）""", """    // serde_derive confirmed; same note as dep_rustc_args)"""),
    ("""    // rustflags 末尾追加：后旗压前旗（dep_rustc_args 同款纪律）""", """    // rustflags appended at end: later flag overrides earlier (same discipline as dep_rustc_args)"""),
    ("""/// 根包测试目标参数。先复用普通 bin 的 Cargo 对齐公共段，再只改两处：""", """/// Root package test target args. First reuse the Cargo-aligned common part of ordinary bin, then change only two places:"""),
    ("""/// - libtest harness 目标用 `--test`，不再显式 `--crate-type=bin`；""", """/// - libtest harness target uses `--test`, no longer explicit `--crate-type=bin`;"""),
    ("""/// - 测试上下文额外看见根 Dev 边。普通根 lib 仍由 root_lib_rustc_args""", """/// - test context additionally sees root Dev edges. Normal root lib is still compiled by root_lib_rustc_args"""),
    ("""///   编译且只消费 Normal 边，正好对应 Cargo 的“双编根 lib”。""", """///   and only consumes Normal edges, exactly matching Cargo's "double-compile root lib"."""),
    ("""        // Cargo 的 harness=false 测试仍设置 cfg(test)，但保留用户 main。""", """        // Cargo harness=false tests still set cfg(test) but keep the user's main."""),
    ("""/// `cargo test` 默认会编译 examples，并在有 integration test 时编译普通 bins，""", """/// `cargo test` compiles examples by default, and compiles ordinary bins when integration tests exist,"""),
    ("""/// 但不会执行它们。这里沿用同一参数主体，以 metadata-only rustc 会话完成""", """/// but doesn't execute them. Here we reuse the same arg body, completing parsing, type-check, and mono collection"""),
    ("""/// 解析、类型检查和 mono 收集；`include_dev` 对应 example=true、普通 bin=false。""", """/// in a metadata-only rustc session; `include_dev` corresponds to example=true, normal bin=false."""),
    ("""/// 根包 lib target 的 rustc 参数（D15 P3 切⑤a full 层迁移面，hexyl 实锤：""", """/// rustc args for root package lib target (D15 P3 cut⑤a full-layer migration surface, hexyl confirmed:"""),
    ("""/// 根包 [lib]+[[bin]] 双 target 时 bin 隐式依赖同名 lib，cargo 先把根 lib""", """/// when root package [lib]+[[bin]] dual targets, bin implicitly depends on same-name lib, cargo first compiles root lib"""),
    ("""/// 编成 target rlib 再让 bin --extern 它--cargo 实证行：根 lib =""", """/// into target rlib then lets bin --extern it--cargo empirical line: root lib ="""),
    ("""/// `--crate-type lib --emit=dep-info,metadata,link` + --extern 指 dep 的""", """/// `--crate-type lib --emit=dep-info,metadata,link` + --extern points to dep's"""),
    ("""/// .rmeta，无 --cap-lints（path 包照常告警））。形态 = dep_rustc_args""", """/// .rmeta, no --cap-lints (path package warns as usual)). Shape = dep_rustc_args"""),
    ("""/// 作用于根 lib（__cless-dep 通道，-Zno-codegen rlib 进 layout.deps），""", """/// applied to root lib (__cless-dep pipeline, -Zno-codegen rlib into layout.deps),"""),
    ("""/// 差异：源/edition/features 取自 manifest/plan（根不是 unit）；check-cfg""", """/// differences: source/edition/features from manifest/plan (root is not a unit); check-cfg"""),
    ("""/// feature 值表 = 声明全集 + 隐式 optional（bin 同款）；--extern 吃""", """/// feature value list = declared full set + implicit optional (same as bin); --extern consumes"""),
    ("""/// root_deps 的 Normal 类边；rustflags 末尾追加（根 lib 是 target 单元，""", """/// Normal-class root_deps edges; rustflags appended at end (root lib is a target unit,"""),
    ("""/// 吃 RUSTFLAGS--cargo --target 语义）。`fp` = root_fingerprint（产物名""", """/// consumes RUSTFLAGS--cargo --target semantics). `fp` = root_fingerprint (artifact name"""),
    ("""/// lib<lib_name>-<fp>.{rmeta,rlib}）。""", """/// lib<lib_name>-<fp>.{rmeta,rlib})."""),
    ("""// 平铺参数先例同 dep_rustc_args""", """// Flat-args precedent same as dep_rustc_args"""),
    ("""    // path 包无 --cap-lints（cargo 同：照常告警）""", """    // path package has no --cap-lints (same as cargo: warns as usual)"""),
    ("""    // extra-filename 窗口纪律同 dep_rustc_args（run_dep_compiler 窗口抠取）""", """    // extra-filename window discipline same as dep_rustc_args (run_dep_compiler window extraction)"""),
    ("""    // host-deps 进 -L（facade 再导出 proc-macro 的 .so 查找--dep 同款注释）""", """    // host-deps goes into -L (lookup for facade re-exported proc-macro .so--same note as dep)"""),
    ("""            continue; // 根普通 lib 不消费 Build/Dev 边""", """            continue; // normal root lib doesn't consume Build/Dev edges"""),
    ("""        // proc-macro 边指 host-deps 的 dylib；普通边照旧 target .rmeta""", """        // proc-macro edge points to host-deps dylib; normal edge remains target .rmeta"""),
    ("""    // rustflags 末尾追加：后旗压前旗（dep_rustc_args 同款纪律）""", """    // rustflags appended at end: later flag overrides earlier (same discipline as dep_rustc_args)"""),
    ("""/// 根 proc-macro 的宿主动态库参数。它不能走 VM 的 `-Zno-codegen`""", """/// Root proc-macro host dynamic lib args. It can't go through the VM `-Zno-codegen`"""),
    ("""/// 通道：后续 integration test 编译时 rustc 必须真实 dlopen 这个产物。""", """/// pipeline: rustc must really dlopen this artifact when compiling subsequent integration tests."""),
    ("""/// 根 lib 的 rustdoc doctest 参数。rustdoc 继续负责 Markdown 提取、行号、""", """/// Root lib rustdoc doctest args. rustdoc continues to handle Markdown extraction, line numbers,"""),
    ("""/// compile_fail 和 harness 汇总；`--test-builder` 只把提取出的临时 crate""", """/// compile_fail, and harness aggregation; `--test-builder` only hands the extracted temporary crate"""),
    ("""/// 改交 mirvm 编译/执行。""", """/// over to mirvm to compile/run."""),
    ("""/// host 闭包普通单元的真 rustc 参数（切②，proc-macro2 实锤形态）：""", """/// Real rustc args for ordinary units in the host closure (cut②, proc-macro2 confirmed shape):"""),
    ("""/// （**无 debuginfo、无 prefer-dynamic**）真 codegen 产 host rlib；""", """/// (**no debuginfo, no prefer-dynamic**) real codegen produces host rlib;"""),
    ("""/// dep 边指 host-deps 的 .rmeta（proc-macro 边指 .so），**只吃 Normal 类边**""", """/// dep edges point to host-deps .rmeta (proc-macro edge points to .so), **only consume Normal-class edges**"""),
    ("""/// （切③ 修正面：Build 边是 build script 的输入，不是本 crate 代码依赖）。""", """/// (cut③ correction side: Build edges are build script input, not this crate's code dependency)."""),
    ("""/// **不带 --sysroot**（真 rustc 用自家 sysroot）、不带任何 -Z。""", """/// **No --sysroot** (real rustc uses its own sysroot), no -Z flags."""),
    ("""/// argv0 = 真 rustc 绝对路径（driver 直接 spawn，不经 __cless-dep）。""", """/// argv0 = real rustc absolute path (driver spawns directly, not via __cless-dep)."""),
    ("""/// proc-macro crate 本体的真 rustc 参数（切②，serde_derive 实锤五钉）：""", """/// Real rustc args for the proc-macro crate itself (cut②, serde_derive confirmed five pins):"""),
    ("""/// -C embed-bitcode=no`（**无 debuginfo**）+ 末尾裸 `--extern proc_macro`""", """/// -C embed-bitcode=no` (**no debuginfo**) + bare `--extern proc_macro` at end"""),
    ("""/// （编译器内建桥 crate）；dep 边指 host-deps 的 .rlib（**真链接**进 dylib），""", """/// (compiler built-in bridge crate); dep edges point to host-deps .rlib (**really linked** into dylib),"""),
    ("""/// **只吃 Normal 类边**（切③ 修正面）。""", """/// **only consume Normal-class edges** (cut③ correction side)."""),
    ("""/// 不带 --sysroot/-Z；argv0 = 真 rustc 绝对路径。""", """/// No --sysroot/-Z; argv0 = real rustc absolute path."""),
    ("""    // 末尾裸 --extern proc_macro：编译器内建桥，从真 rustc 自家 sysroot 解析""", """    // bare --extern proc_macro at end: compiler built-in bridge, resolved from real rustc's own sysroot"""),
    ("""/// build script 编译的真 rustc 参数（切③，E2 实证形态--registry 行）：""", """/// Real rustc args for build script compilation (cut③, E2 empirical shape--registry line):"""),
    ("""/// `--crate-name build_script_build --edition=<e> <build.rs 路径>`""", """/// `--crate-name build_script_build --edition=<e> <build.rs path>`"""),
    ("""/// --crate-type bin --emit=dep-info,link -C embed-bitcode=no`，加 feature""", """/// --crate-type bin --emit=dep-info,link -C embed-bitcode=no`, plus feature"""),
    ("""/// cfgs、`--check-cfg cfg(docsrs,test)` 与 `cfg(feature, values(...))`、""", """/// cfgs, `--check-cfg cfg(docsrs,test)` and `cfg(feature, values(...))`,"""),
    ("""/// profile 旗、`-C metadata/extra-filename`、`--out-dir <build/<pkg>-<fp>>`、""", """/// profile flags, `-C metadata/extra-filename`, `--out-dir <build/<pkg>-<fp>>`,"""),
    ("""/// `-L dependency=<host-deps>`，以及 **Build 类边** --extern 指 host-deps""", """/// `-L dependency=<host-deps>`, and **Build-class edge** --extern points to host-deps"""),
    ("""/// 产物（proc-macro build-dep 指 .so--extern_path 已分派）。""", """/// artifacts (proc-macro build-dep points to .so--extern_path dispatches)."""),
    ("""/// registry 加 --cap-lints allow（cap-lints 已兜住 unexpected_cfgs，feature""", """/// Registry adds --cap-lints allow (cap-lints already covers unexpected_cfgs, feature"""),
    ("""/// 值表 v1 只填已启用 feature--cargo 是声明全集 + 隐式 optional，path 包""", """/// value list v1 only fills enabled features--cargo uses declared full set + implicit optional, path package"""),
    ("""/// build.rs 用未启用 feature 的 cfg 会多一条 unexpected_cfgs，夹具不触，""", """/// build.rs using cfg of an unenabled feature adds one unexpected_cfgs, fixtures don't hit it,"""),
    ("""/// 记档）。无 --sysroot/-Z（真 rustc 自家 sysroot）；无 incremental（cargo""", """/// documented). No --sysroot/-Z (real rustc's own sysroot); no incremental (cargo"""),
    ("""/// 只对 path 包开，属内部优化不复制）。argv0 = 真 rustc 绝对路径。""", """/// only enables for path packages, internal optimization not copied). argv0 = real rustc absolute path."""),
    ("""            continue; // build script 只吃 Build 类边（build-deps）""", """            continue; // build script only consumes Build-class edges (build-deps)"""),
    ("""/// 根包 build script 编译参数（根不是 unit：feature/边表来自 manifest 与""", """/// Root package build script compile args (root is not a unit: feature/edge list from manifest and"""),
    ("""/// plan.root_deps；feature 值表用 manifest.check_cfg_feature_values()--""", """/// plan.root_deps; feature value list uses manifest.check_cfg_feature_values()--"""),
    ("""/// 声明全集 + 隐式 optional，与 cargo 精确一致）。`fp` = root_fingerprint。""", """/// declared full set + implicit optional, exactly matches cargo). `fp` = root_fingerprint."""),
    ("""        // b、c 依赖 a；根依赖 b、c""", """        // b and c depend on a; root depends on b and c"""),
    ("""        assert!(pos(0) < pos(1), "a 必须先于 b: {order:?}");""", """        assert!(pos(0) < pos(1), "a must come before b: {order:?}");"""),
    ("""        assert!(pos(0) < pos(2), "a 必须先于 c: {order:?}");""", """        assert!(pos(0) < pos(2), "a must come before c: {order:?}");"""),
    ("""    // ---- 切⑤c：run_scheduler（Kahn 就绪队列并行调度核）----""", """    // ---- cut⑤c: run_scheduler (Kahn ready-queue parallel scheduler core) ----"""),
    ("""    // 测试与 plan 解耦：直写「每 unit 的 dep 下标表」，按 dep_graph 同纪律""", """    // Tests decoupled from plan: directly write "dep index table per unit", following same discipline as dep_graph"""),
    ("""    // （下标升序逐边推入，重复边重复计）展开成 (dependents, indeg)。""", """    // (push edges in ascending index order, duplicate edges counted repeatedly) expand into (dependents, indeg)."""),
    ("""    /// 菱形 + 独立点 + 重复边，jobs=4：任何 unit 不会在其依赖前开工""", """    /// Diamond + isolated point + duplicate edges, jobs=4: no unit starts before its deps"""),
    ("""    /// （worker 内核对，违例成 Err 浮出水面），且全 unit 完成入 state。""", """    /// (worker kernel check, violation surfaces as Err), and all units completed enter state."""),
    ("""                            return Err(format!("unit {ix} 开工时依赖 {dep} 未完成"));""", """                            return Err(format!("unit {ix} dependency {dep} not completed when starting"));"""),
    ("""        assert_eq!(got, (0..n).collect::<Vec<_>>(), "全 unit 完成: {got:?}");""", """        assert_eq!(got, (0..n).collect::<Vec<_>>(), "all units completed: {got:?}");"""),
    ("""    /// jobs=1 的派发序必须与 Kahn FIFO（topo_order 同纪律）逐位一致--""", """    /// jobs=1 dispatch order must match Kahn FIFO (same discipline as topo_order) exactly--"""),
    ("""    /// 对拍调试锚（注释钉在 run_scheduler 头注）。""", """    /// comparison debug anchor (note pinned in run_scheduler header)."""),
    ("""        // a←b, a←c；{b,c}←d；e 独立。手工 Kahn FIFO：播种 [0,4] → 0 完成""", """        // a←b, a←c; {b,c}←d; e isolated. Manual Kahn FIFO: seed [0,4] → 0 done"""),
    ("""        // 放 1,2 → 4 → 1 → 2（放 3）→ 3""", """        // push 1,2 → 4 → 1 → 2 (push 3) → 3"""),
    ("""    /// 失败语义（jobs=1 链 0→1→2，1/2 皆炸）：第一枚错误保留，失败后""", """    /// Failure semantics (jobs=1 chain 0→1→2, both 1/2 fail): first error retained, after failure"""),
    ("""    /// 停发新活（2 从不开工）。""", """    /// stop issuing new work (2 never starts)."""),
    ("""        assert_eq!(r.unwrap_err(), "boom-1", "第一枚错误保留");""", """        assert_eq!(r.unwrap_err(), "boom-1", "first error retained");"""),
    ("""        assert_eq!(*started.lock().unwrap(), vec![0, 1], "失败后停发新活");""", """        assert_eq!(*started.lock().unwrap(), vec![0, 1], "stop issuing new work after failure");"""),
    ("""    /// 依赖图有环：无活可发也收不齐 → 响亮报错（与 topo_order 同文案）。""", """    /// Dependency graph has a cycle: can't issue or collect all → loud error (same message as topo_order)."""),
    ("""        let deps: &[&[usize]] = &[&[1], &[0]]; // 0↔1 环""", """        let deps: &[&[usize]] = &[&[1], &[0]]; // 0↔1 cycle"""),
    ("""            "内部不一致：编译单元依赖图有环（cargo 解析图本应为 DAG）"""", """            "Internal inconsistency: compilation-unit dependency graph has a cycle (cargo resolve should be a DAG)"""),
    ("""        // b 自身字段一字不动，只改其传递 dep a 的 feature 集 ⇒ b 的 fp 必须变""", """        // b's own fields unchanged, only change transitive dep a's feature set ⇒ b's fp must change"""),
    ("""        // （depsimage pre-key「传递闭包变更 ⇒ 直接依赖产物盖戳变」不变量）""", """        // (depsimage pre-key invariant "transitive closure change ⇒ direct dependency artifact fingerprint changes")"""),
    ("""        assert_ne!(fps0[0], fps1[0], "a 自身 fp 应变");""", """        assert_ne!(fps0[0], fps1[0], "a's own fp should change");"""),
    ("""        assert_ne!(fps0[1], fps1[1], "a 变 ⇒ b 的 fp 必须变（传递传播）");""", """        assert_ne!(fps0[1], fps1[1], "a change ⇒ b's fp must change (transitive propagation)");"""),
    ("""        assert_ne!(fps0[2], fps1[2], "a 变 ⇒ c 的 fp 必须变（传递传播）");""", """        assert_ne!(fps0[2], fps1[2], "a change ⇒ c's fp must change (transitive propagation)");"""),
    ("""        // sysroot_stamp 与 profile 也进 fp""", """        // sysroot_stamp and profile also enter fp"""),
    ("""        assert_ne!(fps0[0], fps2[0], "sysroot_stamp 进 fp");""", """        assert_ne!(fps0[0], fps2[0], "sysroot_stamp enters fp");"""),
    ("""        assert_ne!(fps0[0], fps3[0], "profile 三员进 fp");""", """        assert_ne!(fps0[0], fps3[0], "profile trio enters fp");"""),
    ("""        assert_ne!(first_fps[0], second_fps[0], "Git commit 必须进入自身指纹");""", """        assert_ne!(first_fps[0], second_fps[0], "Git commit must enter its own fingerprint");"""),
    ("""            "Git commit 变化必须沿依赖边传播"""", """            "Git commit change must propagate along dependency edges"""),
    ("""        // registry 单元 cap-lints；feature --cfg 两槽形态""", """        // registry unit cap-lints; feature --cfg two-slot shape"""),
    ("""        // extra-filename 必须是 -C 的下一个独立 argv 槽（run_dep_compiler 窗口抠取）""", """        // extra-filename must be next independent argv slot after -C (run_dep_compiler window extraction)"""),
    ("""            "缺 -C/extra-filename 窗口: {a:?}"""", """            "missing -C/extra-filename window: {a:?}"""),
    ("""        // --extern 指向 dep 的 .rmeta（两槽 cargo 形态）""", """        // --extern points to dep .rmeta (two-slot cargo shape)"""),
    ("""            "缺 --extern: {a:?}"""", """            "missing --extern: {a:?}"""),
    ("""        // dev profile 默认：debug-assertions/overflow-checks 开，无 opt-level""", """        // dev profile default: debug-assertions/overflow-checks on, no opt-level"""),
    ("""        assert_ne!(plain_fps[1], lint_fps[1], "lint 配置必须进入 unit 指纹");""", """        assert_ne!(plain_fps[1], lint_fps[1], "lint config must enter unit fingerprint");"""),
    ("""            "缺 feature 值表 check-cfg: {a:?}"""", """            "missing feature value check-cfg: {a:?}"""),
    ("""        // 根边 --extern 用 .rlib；无 -Z 旗、无 --out-dir、无 -C metadata""", """        // root edge --extern uses .rlib; no -Z flag, no --out-dir, no -C metadata"""),
    ("""    /// proc-macro 场景（serde 家族形状）：shared 双用（bin 与 my_derive 都""", """    /// proc-macro scenario (serde family shape): shared dual-use (used by both bin and my_derive"""),
    ("""    /// 用）、pm_helper 仅 host、my_derive = proc-macro、uses_pm 是带""", """    /// used), pm_helper host-only, my_derive = proc-macro, uses_pm is an ordinary"""),
    ("""    /// proc-macro 边的普通 target dep。""", """    /// target dep with a proc-macro edge."""),
    ("""        assert_eq!(host, BTreeSet::from([0, 1, 2]), "proc-macro 闭包全进 host");""", """        assert_eq!(host, BTreeSet::from([0, 1, 2]), "proc-macro closure all into host");"""),
    ("""            "proc-macro 本体与其独有依赖（pm_helper）不进 target 集"""", """            "proc-macro itself and its unique dep (pm_helper) not in target set"""),
    ("""            "双用 unit（shared）两侧都在"""", """            "dual-use unit (shared) present on both sides"""),
    ("""        assert!(a[0].ends_with("bin/rustc"), "argv0 = 真 rustc: {}", a[0]);""", """        assert!(a[0].ends_with("bin/rustc"), "argv0 = real rustc: {}", a[0]);"""),
    ("""        // 无 debuginfo、无 --sysroot、无 -Z""", """        // no debuginfo, no --sysroot, no -Z"""),
    ("""        // 末尾裸 --extern proc_macro（最后一钉）""", """        // bare --extern proc_macro at end (final pin)"""),
    ("""        // dep 边指 host-deps 的 .rlib（真链接）""", """        // dep edges point to host-deps .rlib (real link)"""),
    ("""        // --out-dir 指 host-deps；registry 单元 cap-lints""", """        // --out-dir points to host-deps; registry unit cap-lints"""),
    ("""        assert!(a[0].ends_with("bin/rustc"), "argv0 = 真 rustc: {}", a[0]);""", """        assert!(a[0].ends_with("bin/rustc"), "argv0 = real rustc: {}", a[0]);"""),
    ("""        // 无 prefer-dynamic、无 debuginfo、无 --sysroot、无 -Z""", """        // no prefer-dynamic, no debuginfo, no --sysroot, no -Z"""),
    ("""        // dep 边指 host-deps 的 .rmeta""", """        // dep edges point to host-deps .rmeta"""),
    ("""        // target dep 的 proc-macro 边 → host-deps 的 dylib；普通边照旧 .rmeta""", """        // target dep's proc-macro edge → host-deps dylib; normal edge remains .rmeta"""),
    ("""            "dep 缺 .so --extern: {a:?}"""", """            "dep missing .so --extern: {a:?}"""),
    ("""        // bin 的 proc-macro 根边 → dylib；普通根边照旧 .rlib""", """        // bin's proc-macro root edge → dylib; normal root edge remains .rlib"""),
    ("""            "bin 缺 .so --extern: {a:?}"""", """            "bin missing .so --extern: {a:?}"""),
    ("""    /// build.rs 场景（切③ 形状）：bdep = Build 类 build-dep（b 的 build.rs""", """    /// build.rs scenario (cut③ shape): bdep = Build-class build-dep (b's build.rs"""),
    ("""    /// 用它）；b 有 build.rs；bdep 自己也有 build.rs 与 build-dep（cc0）。""", """    /// uses it); b has build.rs; bdep itself also has build.rs and build-dep (cc0)."""),
    ("""                // 根也声明了一个 build-dep（根有 build.rs 时才是种子）""", """                // root also declared a build-dep (only a seed when root has build.rs)"""),
    ("""        // 根无 build.rs：种子只有 b 的 Build 边 → bdep；闭包内沿全边扩到 cc0""", """        // root has no build.rs: seeds only b's Build edge → bdep; closure expands along all edges to cc0"""),
    ("""        // 根有 build.rs：根的 Build 边同样是种子（结果集相同--bdep 共享）""", """        // root has build.rs: root's Build edge also a seed (same result set--bdep shared)"""),
    ("""        // 根无 build.rs 且无人有 build.rs → 空集（孤儿 build-dep 不编）""", """        // root has no build.rs and no unit has build.rs → empty set (orphan build-dep not compiled)"""),
    ("""        // target 集不吃 Build 边：b 在，bdep/cc0 不在""", """        // target set doesn't consume Build edges: b in, bdep/cc0 out"""),
    ("""        // b 的 target 编译：--extern 不吃 Build 边（bdep 不出现）""", """        // b's target compile: --extern doesn't consume Build edges (bdep absent)"""),
    ("""            "Build 边漏进 lib 参数: {a:?}"""", """            "Build edge leaked into lib args: {a:?}"""),
    ("""        // b 的 build script 编译：--extern 只吃 Build 边（bdep → host-deps rlib）""", """        // b's build script compile: --extern only consumes Build edges (bdep → host-deps rlib)"""),
    ("""        assert!(bs[0].ends_with("bin/rustc"), "argv0 = 真 rustc: {}", bs[0]);""", """        assert!(bs[0].ends_with("bin/rustc"), "argv0 = real rustc: {}", bs[0]);"""),
    ("""            "缺 feature 值表 check-cfg: {bs:?}"""", """            "missing feature value check-cfg: {bs:?}"""),
    ("""            "build script --out-dir 形态: {bs:?}"""", """            "build script --out-dir shape: {bs:?}"""),
    ("""            "build script 缺 Build 边 --extern: {bs:?}"""", """            "build script missing Build-edge --extern: {bs:?}"""),
    ("""        // registry 单元 cap-lints（E2 形态）；默认 build.rs 路径""", """        // registry unit cap-lints (E2 shape); default build.rs path"""),
    ("""        // bin 会话同样不吃 Build 边""", """        // bin session also doesn't consume Build edges"""),
    ("""            "Build 边漏进 bin 参数: {a:?}"""", """            "Build edge leaked into bin args: {a:?}"""),
    ("""        // 本包 bo：-L 自身 + -l + link-arg + --cfg + --check-cfg + 汇集 -L""", """        // this package bo: -L self + -l + link-arg + --cfg + --check-cfg + collected -L"""),
    ("""        // 无 bo 时这些旗一律不在（传播面只经显式参数）""", """        // without bo these flags are absent (propagation only via explicit args)"""),
    ("""    /// rustflags（D15 P3 切⑤a）：逐条按序进全部 unit fp；target 侧参数""", """    /// rustflags (D15 P3 cut⑤a): enter all unit fps in order; target-side args"""),
    ("""    /// 末尾追加（dep 在 -Z 旗之后、bin 在 --sysroot 之后）。host 侧三个""", """    /// appended at end (dep after -Z flags, bin after --sysroot). The three host-side"""),
    ("""    /// 参数函数签名不含 rustflags--不吃旗由编译期保证，无需断言。""", """    /// arg function signatures don't include rustflags--non-consumption is guaranteed at compile time, no assert needed."""),
    ("""        assert_ne!(fps0[0], fps1[0], "rustflags 进 unit fp");""", """        assert_ne!(fps0[0], fps1[0], "rustflags enter unit fp");"""),
    ("""        assert_ne!(fps0[1], fps1[1], "rustflags 进 unit fp（传递侧同样变）");""", """        assert_ne!(fps0[1], fps1[1], "rustflags enter unit fp (transitive side also changes)");"""),
    ("""        // 顺序有语义：旗序不同 fp 不同（后旗压前旗，不是集合）""", """        // order has semantics: different flag order gives different fp (later flag overrides earlier, not a set)"""),
    ("""        assert_ne!(fps1[0], fps2[0], "rustflags 按序进 fp（不排序）");""", """        assert_ne!(fps1[0], fps2[0], "rustflags enter fp in order (not sorted)");"""),
    ("""        // dep：rustflags 在 -Z 旗之后（参数串末尾）""", """        // dep: rustflags after -Z flags (end of arg list)"""),
    ("""        // registry 单元内置已有一枚 --cap-lints（与 RUSTFLAGS 并存，实证 serde""", """        // registry unit already has one built-in --cap-lints (coexists with RUSTFLAGS, serde line"""),
    ("""        // 行同款两枚形态）--rustflags 段的断言必须取最后一枚""", """        // empirically shows two of the same shape)--rustflags section assert must take the last one"""),
    ("""        assert!(rfpos > zpos, "rustflags 必须在 -Z 旗之后: {a:?}");""", """        assert!(rfpos > zpos, "rustflags must be after -Z flags: {a:?}");"""),
    ("""        assert_eq!(&a[a.len() - 2..], &["--cap-lints", "allow"], "末尾追加");""", """        assert_eq!(&a[a.len() - 2..], &["--cap-lints", "allow"], "appended at end");"""),
    ("""        // bin：rustflags 在 --sysroot 之后（参数串末尾）""", """        // bin: rustflags after --sysroot (end of arg list)"""),
    ("""        assert!(rfpos > syspos, "rustflags 必须在 --sysroot 之后: {a:?}");""", """        assert!(rfpos > syspos, "rustflags must be after --sysroot: {a:?}");"""),
    ("""        assert_eq!(&a[a.len() - 2..], &["--cap-lints", "allow"], "末尾追加");""", """        assert_eq!(&a[a.len() - 2..], &["--cap-lints", "allow"], "appended at end");"""),
    ("""        // 空 rustflags：参数串与此前形态一字不差（无旗路径零漂移）""", """        // empty rustflags: arg list byte-identical to previous shape (zero drift on no-flag path)"""),
    ("""    /// 根包 lib target（切⑤a full 层迁移面，hexyl 实锤）：root_lib 参数""", """    /// Root package lib target (cut⑤a full-layer migration surface, hexyl confirmed): root_lib arg"""),
    ("""    /// 形态 = dep 参数作用于根（__cless-dep/-Z/-C metadata 窗口/.rmeta""", """    /// shape = dep args applied to root (__cless-dep/-Z/-C metadata window/.rmeta"""),
    ("""    /// --extern），差异钉 = 无 --cap-lints（path 包）、feature 值表 check-cfg""", """    /// --extern), difference pins = no --cap-lints (path package), feature value check-cfg"""),
    ("""    /// 在场、rustflags 末尾追加；root_fingerprint 随 rustflags 变；bin 会话""", """    /// present, rustflags appended at end; root_fingerprint changes with rustflags; bin session"""),
    ("""    /// 补根 lib --extern 指 .rlib。""", """    /// adds root lib --extern pointing to .rlib."""),
    ("""        // root_fingerprint 对根源目录盖戳（source_stamp_dir）--目录必须实存""", """        // root_fingerprint fingerprints root source dir (source_stamp_dir)--dir must actually exist"""),
    ("""        assert_ne!(rfp0, rfp1, "rustflags 进 root_fingerprint");""", """        assert_ne!(rfp0, rfp1, "rustflags enter root_fingerprint");"""),
    ("""        // extra-filename 窗口（run_dep_compiler 抠取形态）""", """        // extra-filename window (run_dep_compiler extraction shape)"""),
    ("""        // feature 值表 check-cfg 在场（bin 同款全集口径）；path 包无 --cap-lints""", """        // feature value check-cfg present (same full-set measure as bin); path package has no --cap-lints"""),
    ("""        // 内置--唯一一枚 --cap-lints 是末尾的 rustflags""", """        // built-in--the only --cap-lints is rustflags at the end"""),
    ("""            "缺 feature 值表 check-cfg: {a:?}"""", """            "missing feature value check-cfg: {a:?}"""),
    ("""            "rustflags 末尾"""", """            "rustflags at end"""),
    ("""        // --extern 吃 root_deps Normal 边指 .rmeta""", """        // --extern consumes root_deps Normal edges pointing to .rmeta"""),
    ("""        // bin 会话补根 lib --extern（指 .rlib，与根边混排同段）""", """        // bin session adds root lib --extern (points to .rlib, mixed in same segment as root edges)"""),
    ("""            "bin 缺根 lib --extern: {a:?}"""", """            "bin missing root lib --extern: {a:?}"""),
    ("""        // 根包目录 remap 在场（file!()/panic Location 相对形 = cargo 的""", """        // root package dir remap present (file!()/panic Location relative = cargo's"""),
    ("""        // cwd=包根相对调用语义，redb_kv/gix_pure 实锤）""", """        // cwd=package-root relative invocation semantics, redb_kv/gix_pure confirmed)"""),
    ("""            "bin 缺根包目录 remap: {a:?}"""", """            "bin missing root package dir remap: {a:?}"""),
    ("""        // 无根 lib 时 extern 缺席（老路径零漂移）""", """        // no root lib: --extern absent (old path zero drift)"""),
    ("""            "无根 lib 时不得有根 lib --extern: {a0:?}"""", """            "no root lib must not have root lib --extern: {a0:?}"""),
]

with open(path, 'r', encoding='utf-8') as f:
    text = f.read()

# Apply longest replacements first to avoid shorter matches shadowing longer ones.
repls = sorted(replacements, key=lambda x: len(x[0]), reverse=True)
for old, new in repls:
    text = text.replace(old, new)

with open(path, 'w', encoding='utf-8') as f:
    f.write(text)

print('translation applied')
