//! `cargoless/lockfile.rs` —— Cargo.lock 读写（D15 P1，设计档 §3.2）。
//!
//! 读：v3/v4 格式（`version = N` 头 + `[[package]]` 表列），path 包无
//! source/checksum；dependency 行形态（`"name"` / `"name version"` /
//! `"name version (source)"`）按字符串松散解析（只取 name 与可选 version）。
//! 写：canonical v4 形态（自解落锁供复现与 cargo --locked 反证，设计档 §5 P1）。
//!
//! P1 子集：git source 的包行见到即响亮拒绝（与 manifest.rs 同纪律）。

// P1 逐切接入中：resolve/audit 后续切片接入后摘除本 allow（设计档 §5）。
#![allow(dead_code)]

use std::path::Path;

/// 一条锁定包。
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LockedPkg {
    pub name: String,
    pub version: semver::Version,
    /// `"registry+https://github.com/rust-lang/crates.io-index"`；path 包为 None。
    pub source: Option<String>,
    pub checksum: Option<String>,
    /// (name, 可选 version 串)——lock 行的依赖引用（同一 name 多版本时消歧用）。
    pub dependencies: Vec<(String, Option<semver::Version>)>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Lockfile {
    pub format_version: u32,
    pub packages: Vec<LockedPkg>,
}

type LErr = String;

impl Lockfile {
    pub fn read(path: &Path) -> Result<Self, LErr> {
        let text = std::fs::read_to_string(path)
            .map_err(|e| format!("读取 {} 失败: {e}", path.display()))?;
        Self::parse(&text)
    }

    pub fn parse(text: &str) -> Result<Self, LErr> {
        #[derive(serde::Deserialize)]
        struct RawLock {
            version: Option<u32>,
            package: Option<Vec<RawPkg>>,
        }
        #[derive(serde::Deserialize)]
        struct RawPkg {
            name: String,
            version: String,
            source: Option<String>,
            checksum: Option<String>,
            dependencies: Option<Vec<String>>,
        }
        let raw: RawLock = toml::from_str(text).map_err(|e| format!("Cargo.lock 解析失败: {e}"))?;
        let format_version = raw.version.unwrap_or(1);
        if !(1..=4).contains(&format_version) {
            return Err(format!("Cargo.lock format version {format_version} 子集外"));
        }
        let mut packages = Vec::new();
        for p in raw.package.unwrap_or_default() {
            if let Some(src) = &p.source
                && !src.starts_with("registry+")
            {
                return Err(format!(
                    "lock 包 {} 的 source 子集外（git 源归 P5，响亮拒绝）: {src}",
                    p.name
                ));
            }
            let version = semver::Version::parse(&p.version)
                .map_err(|e| format!("lock 包 {} 版本非法 {}: {e}", p.name, p.version))?;
            let dependencies = p
                .dependencies
                .unwrap_or_default()
                .into_iter()
                .map(|line| parse_dep_line(&line))
                .collect::<Result<Vec<_>, _>>()?;
            packages.push(LockedPkg {
                name: p.name,
                version,
                source: p.source,
                checksum: p.checksum,
                dependencies,
            });
        }
        Ok(Self {
            format_version,
            packages,
        })
    }

    /// 按名找全部锁定版本（同名多版本并存在 lock 中合法）。
    pub fn find(&self, name: &str) -> Vec<&LockedPkg> {
        self.packages.iter().filter(|p| p.name == name).collect()
    }

    /// 精确查找。
    pub fn get(&self, name: &str, version: &semver::Version) -> Option<&LockedPkg> {
        self.packages
            .iter()
            .find(|p| p.name == name && p.version == *version)
    }

    /// canonical v4 序列化（自解落锁用；包按 (name, version) 排序保证确定性）。
    pub fn serialize(&self) -> String {
        let mut out = String::from(
            "# This file is automatically @generated by mirvm cargoless.\n\
             # It is not intended for manual editing.\nversion = 4\n",
        );
        let mut pkgs: Vec<&LockedPkg> = self.packages.iter().collect();
        pkgs.sort_by(|a, b| {
            a.name
                .cmp(&b.name)
                .then(a.version.cmp(&b.version))
                .then(a.source.cmp(&b.source))
        });
        for p in pkgs {
            out.push_str("\n[[package]]\n");
            out.push_str(&format!("name = \"{}\"\n", p.name));
            out.push_str(&format!("version = \"{}\"\n", p.version));
            if let Some(src) = &p.source {
                out.push_str(&format!("source = \"{src}\"\n"));
            }
            if let Some(sum) = &p.checksum {
                out.push_str(&format!("checksum = \"{sum}\"\n"));
            }
            if !p.dependencies.is_empty() {
                let mut deps: Vec<String> = p
                    .dependencies
                    .iter()
                    .map(|(n, v)| match v {
                        Some(v) => format!("\"{n} {v}\""),
                        None => format!("\"{n}\""),
                    })
                    .collect();
                deps.sort();
                out.push_str(&format!("dependencies = [\n {}\n]\n", deps.join(",\n ")));
            }
        }
        out
    }
}

/// lock 依赖行：`"name"` / `"name version"` / `"name version (source)"`。
fn parse_dep_line(line: &str) -> Result<(String, Option<semver::Version>), LErr> {
    let line = line.trim();
    let without_src = line
        .strip_suffix(')')
        .and_then(|l| l.split_once(" ("))
        .map(|(l, _)| l)
        .unwrap_or(line);
    let mut it = without_src.split_whitespace();
    let name = it
        .next()
        .ok_or_else(|| format!("lock 依赖行非法: {line}"))?;
    let version = it
        .next()
        .map(|v| {
            semver::Version::parse(v).map_err(|e| format!("lock 依赖行 {line} 版本非法 {v}: {e}"))
        })
        .transpose()?;
    Ok((name.to_string(), version))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_v4_lock_with_registry_and_path_packages() {
        let lf = Lockfile::parse(
            r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "demo"
version = "0.1.0"
dependencies = [
 "anyhow",
 "local 0.2.0",
]

[[package]]
name = "anyhow"
version = "1.0.103"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1b1c0055b1c8f8e3f4a8b1d2c3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2"

[[package]]
name = "local"
version = "0.2.0"
"#,
        )
        .unwrap();
        assert_eq!(lf.format_version, 4);
        assert_eq!(lf.packages.len(), 3);
        let demo = lf.get("demo", &semver::Version::new(0, 1, 0)).unwrap();
        assert_eq!(demo.source, None);
        assert_eq!(
            demo.dependencies,
            vec![
                ("anyhow".to_string(), None),
                ("local".to_string(), Some(semver::Version::new(0, 2, 0)))
            ]
        );
        let anyhow = &lf.find("anyhow")[0];
        assert!(anyhow.source.as_ref().unwrap().starts_with("registry+"));
        assert!(anyhow.checksum.is_some());
        assert_eq!(lf.find("local")[0].source, None);
    }

    #[test]
    fn rejects_git_source_loudly() {
        let err = Lockfile::parse(
            "version = 4\n\n[[package]]\nname = \"g\"\nversion = \"0.1.0\"\n\
             source = \"git+https://github.com/x/y#abc\"\n",
        )
        .unwrap_err();
        assert!(err.contains("P5"), "{err}");
    }

    #[test]
    fn serialize_roundtrips_deterministically() {
        let lf = Lockfile {
            format_version: 4,
            packages: vec![
                LockedPkg {
                    name: "b".into(),
                    version: semver::Version::new(1, 0, 0),
                    source: Some("registry+https://github.com/rust-lang/crates.io-index".into()),
                    checksum: Some("deadbeef".into()),
                    dependencies: vec![("a".into(), None)],
                },
                LockedPkg {
                    name: "a".into(),
                    version: semver::Version::new(0, 2, 0),
                    source: None,
                    checksum: None,
                    dependencies: vec![],
                },
            ],
        };
        let text = lf.serialize();
        let back = Lockfile::parse(&text).unwrap();
        assert_eq!(back.packages.len(), 2);
        assert_eq!(back.packages[0].name, "a"); // 排序确定性
        let mut sorted = lf.clone();
        sorted.packages.sort_by(|x, y| {
            x.name
                .cmp(&y.name)
                .then(x.version.cmp(&y.version))
                .then(x.source.cmp(&y.source))
        });
        assert_eq!(back, sorted);
        assert_eq!(lf.serialize(), text); // 幂等
    }

    #[test]
    fn parses_repo_own_lockfile() {
        // 仓内真 Cargo.lock（v4 + 数百包）必须能完整解析
        let lf = Lockfile::read(
            Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("Cargo.lock")
                .as_path(),
        )
        .unwrap();
        assert!(lf.packages.len() > 100);
        assert!(lf.get("mirvm", &semver::Version::new(0, 0, 1)).is_some());
        assert!(
            lf.packages
                .iter()
                .all(|p| { p.source.as_ref().is_none_or(|s| s.starts_with("registry+")) })
        );
    }
}
