//! `cargoless/lockfile.rs` —— Cargo.lock 读写（D15 P1，设计档 §3.2）。
//!
//! 读：v3/v4 格式（`version = N` 头 + `[[package]]` 表列），path 包无
//! source/checksum；dependency 行形态（`"name"` / `"name version"` /
//! `"name version (source)"`）按字符串松散解析（只取 name 与可选 version）。
//! 写：保留模型指定的 v3/v4 头，包行使用两者共通的 canonical 形态（自解落锁
//! 供复现与 cargo --locked 反证，设计档 §5 P1）。
//!
//! source 支持 crates.io registry 与精确 Git commit；Git 包没有 checksum。

// P1 逐切接入中：resolve/audit 后续切片接入后摘除本 allow（设计档 §5）。
#![allow(dead_code)]

use std::path::Path;

/// 一条锁定包。
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LockedPkg {
    pub name: String,
    pub version: semver::Version,
    /// `"registry+https://github.com/rust-lang/crates.io-index"`；path 包为 None。
    pub source: Option<String>,
    pub checksum: Option<String>,
    /// lock 行的依赖引用；同名包按 version，仍重名时再按 source 消歧。
    pub dependencies: Vec<LockedDep>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct LockedDep {
    pub name: String,
    pub version: Option<semver::Version>,
    pub source: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Lockfile {
    pub format_version: u32,
    pub packages: Vec<LockedPkg>,
}

type LErr = String;

impl Lockfile {
    pub fn read(path: &Path) -> Result<Self, LErr> {
        let text = std::fs::read_to_string(path)
            .map_err(|e| format!("读取 {} 失败: {e}", path.display()))?;
        Self::parse(&text)
    }

    pub fn parse(text: &str) -> Result<Self, LErr> {
        #[derive(serde::Deserialize)]
        struct RawLock {
            version: Option<u32>,
            package: Option<Vec<RawPkg>>,
        }
        #[derive(serde::Deserialize)]
        struct RawPkg {
            name: String,
            version: String,
            source: Option<String>,
            checksum: Option<String>,
            dependencies: Option<Vec<String>>,
        }
        let raw: RawLock = toml::from_str(text).map_err(|e| format!("Cargo.lock 解析失败: {e}"))?;
        let format_version = raw.version.unwrap_or(1);
        if !(1..=4).contains(&format_version) {
            return Err(format!("Cargo.lock format version {format_version} 子集外"));
        }
        let mut packages = Vec::new();
        for p in raw.package.unwrap_or_default() {
            if let Some(src) = &p.source
                && !src.starts_with("registry+")
                && !src.starts_with("git+")
            {
                return Err(format!("lock 包 {} 的 source 子集外: {src}", p.name));
            }
            if p.source
                .as_deref()
                .is_some_and(|source| source.starts_with("git+"))
            {
                let source = p.source.as_deref().unwrap();
                let precise = source.rsplit_once('#').map(|(_, precise)| precise);
                if !precise.is_some_and(|precise| {
                    matches!(precise.len(), 40 | 64)
                        && precise.bytes().all(|byte| byte.is_ascii_hexdigit())
                }) {
                    return Err(format!(
                        "lock Git 包 {} 的 source 缺少 40/64 位精确 commit: {source}",
                        p.name
                    ));
                }
                if p.checksum.is_some() {
                    return Err(format!("lock Git 包 {} 不应带 checksum", p.name));
                }
            }
            let version = semver::Version::parse(&p.version)
                .map_err(|e| format!("lock 包 {} 版本非法 {}: {e}", p.name, p.version))?;
            let dependencies = p
                .dependencies
                .unwrap_or_default()
                .into_iter()
                .map(|line| parse_dep_line(&line))
                .collect::<Result<Vec<_>, _>>()?;
            packages.push(LockedPkg {
                name: p.name,
                version,
                source: p.source,
                checksum: p.checksum,
                dependencies,
            });
        }
        Ok(Self {
            format_version,
            packages,
        })
    }

    /// 按名找全部锁定版本（同名多版本并存在 lock 中合法）。
    pub fn find(&self, name: &str) -> Vec<&LockedPkg> {
        self.packages.iter().filter(|p| p.name == name).collect()
    }

    /// 精确查找。
    pub fn get(&self, name: &str, version: &semver::Version) -> Option<&LockedPkg> {
        self.packages
            .iter()
            .find(|p| p.name == name && p.version == *version)
    }

    /// canonical v3/v4 序列化（自解落锁用；包按 (name, version) 排序保证确定性）。
    pub fn serialize(&self) -> String {
        debug_assert!(matches!(self.format_version, 3 | 4));
        let mut out = format!(
            "# This file is automatically @generated by mirvm cargoless.\n\
             # It is not intended for manual editing.\nversion = {}\n",
            self.format_version
        );
        let mut pkgs: Vec<&LockedPkg> = self.packages.iter().collect();
        pkgs.sort_by(|a, b| {
            a.name
                .cmp(&b.name)
                .then(a.version.cmp(&b.version))
                .then(a.source.cmp(&b.source))
        });
        for p in pkgs {
            out.push_str("\n[[package]]\n");
            out.push_str(&format!("name = \"{}\"\n", p.name));
            out.push_str(&format!("version = \"{}\"\n", p.version));
            if let Some(src) = &p.source {
                out.push_str(&format!("source = \"{src}\"\n"));
            }
            if let Some(sum) = &p.checksum {
                out.push_str(&format!("checksum = \"{sum}\"\n"));
            }
            if !p.dependencies.is_empty() {
                // cargo canonical：每行带尾逗号（含末行）——--locked 对非
                // canonical lock 一律判"需重写"而拒（c_serde_json 实锤）
                let mut lines: Vec<String> = p
                    .dependencies
                    .iter()
                    .map(
                        |dependency| match (&dependency.version, &dependency.source) {
                            (Some(version), Some(source)) => {
                                format!(" \"{} {} ({})\",", dependency.name, version, source)
                            }
                            (Some(version), None) => {
                                format!(" \"{} {}\",", dependency.name, version)
                            }
                            (None, None) => format!(" \"{}\",", dependency.name),
                            (None, Some(_)) => unreachable!("source 消歧必须同时带 version"),
                        },
                    )
                    .collect();
                lines.sort();
                out.push_str(&format!("dependencies = [\n{}\n]\n", lines.join("\n")));
            }
        }
        out
    }
}

/// lock 依赖行：`"name"` / `"name version"` / `"name version (source)"`。
fn parse_dep_line(line: &str) -> Result<LockedDep, LErr> {
    let line = line.trim();
    let (without_src, source) = line
        .strip_suffix(')')
        .and_then(|l| l.split_once(" ("))
        .map(|(line, source)| (line, Some(source.to_string())))
        .unwrap_or((line, None));
    let mut it = without_src.split_whitespace();
    let name = it
        .next()
        .ok_or_else(|| format!("lock 依赖行非法: {line}"))?;
    let version = it
        .next()
        .map(|v| {
            semver::Version::parse(v).map_err(|e| format!("lock 依赖行 {line} 版本非法 {v}: {e}"))
        })
        .transpose()?;
    if source.is_some() && version.is_none() {
        return Err(format!("lock 依赖行带 source 时必须带 version: {line}"));
    }
    if let Some(source) = &source {
        if !source.starts_with("registry+") && !source.starts_with("git+") {
            return Err(format!("lock 依赖行 source 子集外: {source}"));
        }
        if source.starts_with("git+") && source.contains('#') {
            return Err(format!(
                "lock Git 依赖行 source 不应带精确 commit fragment: {source}"
            ));
        }
    }
    Ok(LockedDep {
        name: name.to_string(),
        version,
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_v4_lock_with_registry_and_path_packages() {
        let lf = Lockfile::parse(
            r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "demo"
version = "0.1.0"
dependencies = [
 "anyhow",
 "local 0.2.0",
]

[[package]]
name = "anyhow"
version = "1.0.103"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1b1c0055b1c8f8e3f4a8b1d2c3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2"

[[package]]
name = "local"
version = "0.2.0"
"#,
        )
        .unwrap();
        assert_eq!(lf.format_version, 4);
        assert_eq!(lf.packages.len(), 3);
        let demo = lf.get("demo", &semver::Version::new(0, 1, 0)).unwrap();
        assert_eq!(demo.source, None);
        assert_eq!(
            demo.dependencies,
            vec![
                LockedDep {
                    name: "anyhow".to_string(),
                    version: None,
                    source: None,
                },
                LockedDep {
                    name: "local".to_string(),
                    version: Some(semver::Version::new(0, 2, 0)),
                    source: None,
                }
            ]
        );
        let anyhow = &lf.find("anyhow")[0];
        assert!(anyhow.source.as_ref().unwrap().starts_with("registry+"));
        assert!(anyhow.checksum.is_some());
        assert_eq!(lf.find("local")[0].source, None);
    }

    #[test]
    fn parses_git_source_with_precise_commit() {
        let lock = Lockfile::parse(
            "version = 4\n\n[[package]]\nname = \"g\"\nversion = \"0.1.0\"\n\
             source = \"git+https://github.com/x/y#0123456789abcdef0123456789abcdef01234567\"\n",
        )
        .unwrap();
        assert_eq!(
            lock.packages[0].source.as_deref(),
            Some("git+https://github.com/x/y#0123456789abcdef0123456789abcdef01234567")
        );
    }

    #[test]
    fn parses_git_dependency_source_without_precise_fragment() {
        let dependency = parse_dep_line(
            "g 0.1.0 (git+https://github.com/x/y?rev=0123456789abcdef0123456789abcdef01234567)",
        )
        .unwrap();
        assert_eq!(dependency.name, "g");
        assert_eq!(dependency.version, Some(semver::Version::new(0, 1, 0)));
        assert_eq!(
            dependency.source.as_deref(),
            Some("git+https://github.com/x/y?rev=0123456789abcdef0123456789abcdef01234567")
        );
    }

    #[test]
    fn rejects_git_source_without_precise_commit() {
        let err = Lockfile::parse(
            "version = 4\n\n[[package]]\nname='g'\nversion='0.1.0'\n\
             source='git+https://github.com/x/y?branch=main'\n",
        )
        .unwrap_err();
        assert!(err.contains("精确 commit"), "{err}");
    }

    #[test]
    fn serialize_roundtrips_deterministically() {
        let lf = Lockfile {
            format_version: 4,
            packages: vec![
                LockedPkg {
                    name: "b".into(),
                    version: semver::Version::new(1, 0, 0),
                    source: Some("registry+https://github.com/rust-lang/crates.io-index".into()),
                    checksum: Some("deadbeef".into()),
                    dependencies: vec![LockedDep {
                        name: "a".into(),
                        version: None,
                        source: None,
                    }],
                },
                LockedPkg {
                    name: "a".into(),
                    version: semver::Version::new(0, 2, 0),
                    source: None,
                    checksum: None,
                    dependencies: vec![],
                },
            ],
        };
        let text = lf.serialize();
        let back = Lockfile::parse(&text).unwrap();
        assert_eq!(back.packages.len(), 2);
        assert_eq!(back.packages[0].name, "a"); // 排序确定性
        let mut sorted = lf.clone();
        sorted.packages.sort_by(|x, y| {
            x.name
                .cmp(&y.name)
                .then(x.version.cmp(&y.version))
                .then(x.source.cmp(&y.source))
        });
        assert_eq!(back, sorted);
        assert_eq!(lf.serialize(), text); // 幂等

        let mut v3 = lf.clone();
        v3.format_version = 3;
        let text = v3.serialize();
        assert!(text.contains("\nversion = 3\n"));
        assert_eq!(Lockfile::parse(&text).unwrap().format_version, 3);
    }

    #[test]
    fn parses_repo_own_lockfile() {
        // 仓内真 Cargo.lock（v4 + 数百包）必须能完整解析
        let lf = Lockfile::read(
            Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("Cargo.lock")
                .as_path(),
        )
        .unwrap();
        assert!(lf.packages.len() > 100);
        assert!(lf.get("mirvm", &semver::Version::new(0, 0, 1)).is_some());
        assert!(
            lf.packages
                .iter()
                .all(|p| { p.source.as_ref().is_none_or(|s| s.starts_with("registry+")) })
        );
    }
}
