#!/usr/bin/env bash
# real-project suite 自身的行为回归。fixture 全在本地生成，不访问网络。
set -u
cd "$(dirname "$0")/.."

TMP=$(mktemp -d)
trap 'test -z "${SERVER_PID:-}" || kill "$SERVER_PID" 2>/dev/null || true; rm -rf "$TMP"' EXIT
PYTHON=${PYTHON:-$(command -v python3)}
pass=0 fail=0
ok() { pass=$((pass + 1)); echo "PASS $*"; }
bad() { fail=$((fail + 1)); echo "FAIL $*"; }

UPSTREAM="$TMP/upstream"
mkdir -p "$UPSTREAM/src"
cat >"$UPSTREAM/Cargo.toml" <<'EOF'
[package]
name = "project-suite-mismatch"
version = "0.1.0"
edition = "2024"
EOF
cat >"$UPSTREAM/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "project-suite-mismatch"
version = "0.1.0"
EOF
cat >"$UPSTREAM/src/main.rs" <<'EOF'
fn main() {
    println!("same-A");
}
EOF
git -C "$UPSTREAM" init -q -b main
git -C "$UPSTREAM" config user.name 'mirvm test'
git -C "$UPSTREAM" config user.email 'mirvm-test@example.invalid'
git -C "$UPSTREAM" add Cargo.toml Cargo.lock src/main.rs
git -C "$UPSTREAM" commit -q -m fixture
REV=$(git -C "$UPSTREAM" rev-parse HEAD)
LOCK_SHA256=$(sha256sum "$UPSTREAM/Cargo.lock" | cut -d' ' -f1)

CASE="$TMP/mismatch.toml"
cat >"$CASE" <<EOF
name = "mismatch"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
subdir = "."
args = []
expected_exit = 0
timeout_seconds = 30
normalizers = []
EOF

FAKE_MIRVM="$TMP/fake-mirvm"
cat >"$FAKE_MIRVM" <<'EOF'
#!/usr/bin/env bash
printf 'same-B\n'
EOF
chmod +x "$FAKE_MIRVM"

SUITE_ROOT="$TMP/suite"
ARTIFACTS="$TMP/artifacts"
HOST_TARGET=$(rustc -vV | sed -n 's/^host: //p')
DEFAULT_SYSROOT_MARKER="$SUITE_ROOT/mirvm-xdg/mirvm/sysroot-$HOST_TARGET/lib/rustlib/$HOST_TARGET/.rustc-build-sysroot-hash"
mkdir -p "$(dirname "$DEFAULT_SYSROOT_MARKER")"
printf 'test sysroot\n' >"$DEFAULT_SYSROOT_MARKER"
common_env=(
    PROJECT_SUITE_ROOT="$SUITE_ROOT"
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS"
    MIRVM="$FAKE_MIRVM"
)

prepare_out=$(env "${common_env[@]}" bash tests/real_projects.sh prepare "$CASE" 2>&1)
prepare_code=$?
if [ "$prepare_code" -ne 0 ]; then
    bad "mismatch fixture prepare (exit=$prepare_code)"
    echo "$prepare_out"
else
    check_out=$(env "${common_env[@]}" bash tests/real_projects.sh check "$CASE" 2>&1)
    check_code=$?
    env "${common_env[@]}" bash tests/real_projects.sh bench "$CASE" \
        >"$TMP/bench.stdout" 2>"$TMP/bench.stderr"
    bench_code=$?

    if [ "$check_code" -ne 0 ] \
        && echo "$check_out" | grep -Fq 'stdout_mismatch' \
        && [ "$bench_code" -ne 0 ] \
        && [ ! -s "$TMP/bench.stdout" ] \
        && grep -Fq 'reason=stdout_mismatch' "$TMP/bench.stderr" \
        && grep -Fq 'correctness_not_passed' "$TMP/bench.stderr" \
        && [ ! -s "$ARTIFACTS/mismatch/bench/samples.jsonl" ]; then
        ok 'stdout 不一致时拒绝 correctness 与 benchmark'
    else
        bad "stdout mismatch gate (check=$check_code bench=$bench_code)"
        echo "--- check ---"
        echo "$check_out"
        echo "--- bench stdout ---"
        cat "$TMP/bench.stdout"
        echo "--- bench stderr ---"
        cat "$TMP/bench.stderr"
        if [ -e "$ARTIFACTS/mismatch/bench/samples.jsonl" ]; then
            echo "--- samples ---"
            cat "$ARTIFACTS/mismatch/bench/samples.jsonl"
        fi
    fi
fi

INVALID_CASE="$TMP/invalid-rev.toml"
cat >"$INVALID_CASE" <<EOF
name = "invalid-rev"
repo = "$UPSTREAM"
rev = "main"
lock_sha256 = "$LOCK_SHA256"
EOF
invalid_out=$(env "${common_env[@]}" bash tests/real_projects.sh \
    prepare "$INVALID_CASE" 2>&1)
invalid_code=$?
if [ "$invalid_code" -ne 0 ] \
    && echo "$invalid_out" | grep -Fq 'invalid_case: rev must be a full 40-hex commit'; then
    ok '非法 case 传播失败状态'
else
    bad "invalid case status (exit=$invalid_code)"
    echo "$invalid_out"
fi

UNKNOWN_ROOT_CASE="$TMP/unknown-root-key.toml"
cat >"$UNKNOWN_ROOT_CASE" <<EOF
name = "unknown-root-key"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
timeout_second = 30
EOF
unknown_root_out=$(env "${common_env[@]}" bash tests/real_projects.sh \
    prepare "$UNKNOWN_ROOT_CASE" 2>&1)
unknown_root_code=$?
if [ "$unknown_root_code" -eq 65 ] \
    && echo "$unknown_root_out" | grep -Fq \
        'invalid_case: unknown key: timeout_second'; then
    ok 'case 拒绝未知顶层字段'
else
    bad "unknown root case key (exit=$unknown_root_code)"
    echo "$unknown_root_out"
fi

UNKNOWN_BENCH_CASE="$TMP/unknown-bench-key.toml"
cat >"$UNKNOWN_BENCH_CASE" <<EOF
name = "unknown-bench-key"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"

[bench]
sample = 1
EOF
unknown_bench_out=$(env "${common_env[@]}" bash tests/real_projects.sh \
    prepare "$UNKNOWN_BENCH_CASE" 2>&1)
unknown_bench_code=$?
if [ "$unknown_bench_code" -eq 65 ] \
    && echo "$unknown_bench_out" | grep -Fq \
        'invalid_case: unknown key: bench.sample'; then
    ok 'case 拒绝未知 bench 字段'
else
    bad "unknown bench case key (exit=$unknown_bench_code)"
    echo "$unknown_bench_out"
fi

UNKNOWN_XFAIL_CASE="$TMP/unknown-xfail-key.toml"
cat >"$UNKNOWN_XFAIL_CASE" <<EOF
name = "unknown-xfail-key"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"

[xfail]
mirvm_exit = 70
diagnostic = "mirvm trap: known.frontier"
diagnostics = "typo"
EOF
unknown_xfail_out=$(env "${common_env[@]}" bash tests/real_projects.sh \
    prepare "$UNKNOWN_XFAIL_CASE" 2>&1)
unknown_xfail_code=$?
if [ "$unknown_xfail_code" -eq 65 ] \
    && echo "$unknown_xfail_out" | grep -Fq \
        'invalid_case: unknown key: xfail.diagnostics'; then
    ok 'case 拒绝未知 xfail 字段'
else
    bad "unknown xfail case key (exit=$unknown_xfail_code)"
    echo "$unknown_xfail_out"
fi

INVALID_XFAIL_DIAGNOSTIC_CASE="$TMP/invalid-xfail-diagnostic.toml"
cat >"$INVALID_XFAIL_DIAGNOSTIC_CASE" <<EOF
name = "invalid-xfail-diagnostic"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"

[xfail]
mirvm_exit = 70
diagnostic = "generic substring"
EOF
invalid_xfail_diagnostic_out=$(env "${common_env[@]}" \
    bash tests/real_projects.sh prepare "$INVALID_XFAIL_DIAGNOSTIC_CASE" 2>&1)
invalid_xfail_diagnostic_code=$?
if [ "$invalid_xfail_diagnostic_code" -eq 65 ] \
    && echo "$invalid_xfail_diagnostic_out" | grep -Fq \
        'invalid_case: xfail.diagnostic must be one canonical mirvm line'; then
    ok 'XFAIL 清单只接受单行 canonical mirvm 诊断'
else
    bad "invalid XFAIL diagnostic (exit=$invalid_xfail_diagnostic_code)"
    echo "$invalid_xfail_diagnostic_out"
fi

XFAIL_CASE="$TMP/xfail.toml"
cat >"$XFAIL_CASE" <<EOF
name = "known-red"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
subdir = "."
args = []
expected_exit = 0
timeout_seconds = 30

[xfail]
mirvm_exit = 70
diagnostic = "mirvm trap: known.frontier"
EOF
FAKE_XFAIL="$TMP/fake-xfail-mirvm"
cat >"$FAKE_XFAIL" <<'EOF'
#!/usr/bin/env bash
echo 'mirvm trap: known.frontier' >&2
exit 70
EOF
chmod +x "$FAKE_XFAIL"
xfail_env=(
    PROJECT_SUITE_ROOT="$SUITE_ROOT"
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS"
    MIRVM="$FAKE_XFAIL"
)
xfail_prepare=$(env "${xfail_env[@]}" bash tests/real_projects.sh \
    prepare "$XFAIL_CASE" 2>&1)
xfail_prepare_code=$?
xfail_out=$(env "${xfail_env[@]}" bash tests/real_projects.sh \
    check "$XFAIL_CASE" 2>&1)
xfail_code=$?
if [ "$xfail_prepare_code" -eq 0 ] && [ "$xfail_code" -eq 0 ] \
    && echo "$xfail_out" | grep -Fq 'XFAIL known-red reason=mirvm trap: known.frontier'; then
    ok '精确诊断命中时记录 XFAIL'
else
    bad "known-red XFAIL (prepare=$xfail_prepare_code check=$xfail_code)"
    echo "$xfail_prepare"
    echo "$xfail_out"
fi

FAKE_GREEN="$TMP/fake-green-mirvm"
cat >"$FAKE_GREEN" <<'EOF'
#!/usr/bin/env bash
printf 'same-A\n'
EOF
chmod +x "$FAKE_GREEN"
xpass_out=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_GREEN" \
    bash tests/real_projects.sh check "$XFAIL_CASE" 2>&1)
xpass_code=$?
if [ "$xpass_code" -ne 0 ] \
    && echo "$xpass_out" | grep -Fq 'XPASS known-red reason=expected_failure_disappeared'; then
    ok '已转绿的 expected-red 报告 XPASS'
else
    bad "known-red XPASS (exit=$xpass_code)"
    echo "$xpass_out"
fi

UPSTREAM_B="$TMP/upstream-b"
mkdir -p "$UPSTREAM_B/src"
cp "$UPSTREAM/Cargo.toml" "$UPSTREAM/Cargo.lock" "$UPSTREAM_B/"
cat >"$UPSTREAM_B/src/main.rs" <<'EOF'
fn main() {
    println!("repo-B");
}
EOF
git -C "$UPSTREAM_B" init -q -b main
git -C "$UPSTREAM_B" config user.name 'mirvm test'
git -C "$UPSTREAM_B" config user.email 'mirvm-test@example.invalid'
git -C "$UPSTREAM_B" add Cargo.toml Cargo.lock src/main.rs
git -C "$UPSTREAM_B" commit -q -m fixture-b

COLLISION_A="$TMP/collision-a.toml"
COLLISION_B="$TMP/collision-b.toml"
cat >"$COLLISION_A" <<EOF
name = "repo-collision"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
EOF
cat >"$COLLISION_B" <<EOF
name = "repo-collision"
repo = "$UPSTREAM_B"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
EOF
collision_a_out=$(env "${common_env[@]}" bash tests/real_projects.sh \
    prepare "$COLLISION_A" 2>&1)
collision_a_code=$?
collision_b_out=$(env "${common_env[@]}" bash tests/real_projects.sh \
    prepare "$COLLISION_B" 2>&1)
collision_b_code=$?
if [ "$collision_a_code" -eq 0 ] && [ "$collision_b_code" -ne 0 ] \
    && echo "$collision_b_out" | grep -Fq 'revision_not_found'; then
    ok 'repo 身份参与 revision provenance'
else
    bad "repo collision provenance (first=$collision_a_code second=$collision_b_code)"
    echo "$collision_a_out"
    echo "$collision_b_out"
fi

BENCH_CASE="$TMP/bench-green.toml"
cat >"$BENCH_CASE" <<EOF
name = "bench-green"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
subdir = "."
args = []
expected_exit = 0
timeout_seconds = 30

[bench]
warmup = 1
samples = 3
EOF
bench_env=(
    PROJECT_SUITE_ROOT="$SUITE_ROOT"
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS"
    MIRVM="$FAKE_GREEN"
)
green_prepare=$(env "${bench_env[@]}" bash tests/real_projects.sh \
    prepare "$BENCH_CASE" 2>&1)
green_prepare_code=$?
env "${bench_env[@]}" bash tests/real_projects.sh bench "$BENCH_CASE" \
    >"$TMP/green-bench.stdout" 2>"$TMP/green-bench.stderr"
green_bench_code=$?
green_samples="$ARTIFACTS/bench-green/bench/samples.jsonl"
green_summary="$ARTIFACTS/bench-green/bench/summary.json"
if [ "$green_prepare_code" -eq 0 ] && [ "$green_bench_code" -eq 0 ] \
    && [ -s "$TMP/green-bench.stdout" ] \
    && cmp -s "$TMP/green-bench.stdout" "$green_summary" \
    && "$PYTHON" - "$TMP/green-bench.stdout" "$green_samples" \
        "$UPSTREAM" "$REV" "$LOCK_SHA256" "$HOST_TARGET" <<'PY'
import json
import pathlib
import sys

summary = json.loads(pathlib.Path(sys.argv[1]).read_text())
samples = [json.loads(line) for line in pathlib.Path(sys.argv[2]).read_text().splitlines()]
repo, revision, lock_sha256, host_target = sys.argv[3:]
assert summary["schema_version"] == 1
assert summary["case"] == "bench-green"
assert summary["repo"] == repo
assert summary["revision"] == revision
assert summary["lock_sha256"] == lock_sha256
assert summary["subdir"] == "."
assert summary["args"] == []
assert summary["env"] == {}
assert summary["expected_exit"] == 0
assert summary["timeout_seconds"] == 30
assert summary["host_target"] == host_target
assert summary["benchmark"] == {"warmup": 1, "samples": 3}
assert set(summary["tools"]) == {"cargo", "rustc", "mirvm"}
for tool in summary["tools"].values():
    assert pathlib.Path(tool["path"]).is_absolute()
    assert len(tool["sha256"]) == 64
    int(tool["sha256"], 16)
assert summary["samples"] == 3
assert summary["unit"] == "ns"
for runner in ("native", "mirvm"):
    assert isinstance(summary[runner]["median_ns"], int)
    assert summary[runner]["median_ns"] > 0
    assert isinstance(summary[runner]["p95_ns"], int)
    assert summary[runner]["p95_ns"] >= summary[runner]["median_ns"]
assert len(samples) == 3
assert [sample["order"] for sample in samples] == [
    "native-first", "mirvm-first", "native-first"
]
assert all(sample["native_ns"] > 0 and sample["mirvm_ns"] > 0 for sample in samples)
PY
then
    ok '正确性通过后输出多样本 benchmark JSON'
else
    bad "green benchmark (prepare=$green_prepare_code bench=$green_bench_code)"
    echo "$green_prepare"
    echo "--- bench stdout ---"
    cat "$TMP/green-bench.stdout"
    echo "--- bench stderr ---"
    cat "$TMP/green-bench.stderr"
    test -e "$green_samples" && cat "$green_samples"
fi

BENCH_REPO_SHA=$(printf '%s' "$UPSTREAM" | sha256sum | cut -d' ' -f1)
BENCH_READY="$SUITE_ROOT/prepared/bench-green/$BENCH_REPO_SHA/$REV.ready"
mv "$BENCH_READY" "$BENCH_READY.saved"
stale_artifact_out=$(env "${bench_env[@]}" bash tests/real_projects.sh \
    check "$BENCH_CASE" 2>&1)
stale_artifact_code=$?
mv "$BENCH_READY.saved" "$BENCH_READY"
if [ "$stale_artifact_code" -ne 0 ] \
    && echo "$stale_artifact_out" | grep -Fq 'case_not_prepared: bench-green' \
    && [ ! -e "$ARTIFACTS/bench-green/check" ]; then
    ok 'check 前置失败会清除旧 artifacts'
else
    bad "stale check artifact (exit=$stale_artifact_code)"
    echo "$stale_artifact_out"
    find "$ARTIFACTS/bench-green/check" -maxdepth 1 -type f -print 2>/dev/null || true
fi

FAKE_SYNC_CARGO="$TMP/fake-sync-cargo"
FAKE_SYNC_MIRVM="$TMP/fake-sync-mirvm"
cat >"$FAKE_SYNC_CARGO" <<'EOF'
#!/usr/bin/env bash
case "${1:-}" in
    fetch|build) exit 0 ;;
    run)
        if [[ "$(pwd)" == *-bench.* ]]; then
            printf 'sync-benchmark\n'
        else
            printf 'sync-correctness\n'
        fi
        ;;
    *) exit 2 ;;
esac
EOF
cat >"$FAKE_SYNC_MIRVM" <<'EOF'
#!/usr/bin/env bash
if [[ "$(pwd)" == *-bench.* ]]; then
    printf 'sync-benchmark\n'
else
    printf 'sync-correctness\n'
fi
EOF
chmod +x "$FAKE_SYNC_CARGO" "$FAKE_SYNC_MIRVM"
SYNC_CASE="$TMP/sync-drift.toml"
cat >"$SYNC_CASE" <<EOF
name = "sync-drift"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"

[bench]
warmup = 1
samples = 2
EOF
sync_prepare=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" CARGO="$FAKE_SYNC_CARGO" \
    MIRVM="$FAKE_SYNC_MIRVM" \
    bash tests/real_projects.sh prepare "$SYNC_CASE" 2>&1)
sync_prepare_code=$?
env PROJECT_SUITE_ROOT="$SUITE_ROOT" PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" \
    CARGO="$FAKE_SYNC_CARGO" MIRVM="$FAKE_SYNC_MIRVM" \
    bash tests/real_projects.sh bench "$SYNC_CASE" \
    >"$TMP/sync-bench.stdout" 2>"$TMP/sync-bench.stderr"
sync_bench_code=$?
sync_samples="$ARTIFACTS/sync-drift/bench/samples.jsonl"
if [ "$sync_prepare_code" -eq 0 ] && [ "$sync_bench_code" -ne 0 ] \
    && [ ! -s "$TMP/sync-bench.stdout" ] \
    && grep -Fq 'reason=benchmark_warmup_oracle_mismatch' "$TMP/sync-bench.stderr" \
    && [ ! -s "$sync_samples" ]; then
    ok 'benchmark 每次观测都固定到 correctness oracle'
else
    bad "benchmark synchronized drift (prepare=$sync_prepare_code bench=$sync_bench_code)"
    echo "$sync_prepare"
    echo "--- stdout ---"
    cat "$TMP/sync-bench.stdout"
    echo "--- stderr ---"
    cat "$TMP/sync-bench.stderr"
    test -e "$sync_samples" && cat "$sync_samples"
fi

SYNC_SAMPLE_CASE="$TMP/sync-sample-drift.toml"
cat >"$SYNC_SAMPLE_CASE" <<EOF
name = "sync-sample-drift"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"

[bench]
warmup = 0
samples = 1
EOF
sync_sample_prepare=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" CARGO="$FAKE_SYNC_CARGO" \
    MIRVM="$FAKE_SYNC_MIRVM" \
    bash tests/real_projects.sh prepare "$SYNC_SAMPLE_CASE" 2>&1)
sync_sample_prepare_code=$?
env PROJECT_SUITE_ROOT="$SUITE_ROOT" PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" \
    CARGO="$FAKE_SYNC_CARGO" MIRVM="$FAKE_SYNC_MIRVM" \
    bash tests/real_projects.sh bench "$SYNC_SAMPLE_CASE" \
    >"$TMP/sync-sample.stdout" 2>"$TMP/sync-sample.stderr"
sync_sample_code=$?
if [ "$sync_sample_prepare_code" -eq 0 ] && [ "$sync_sample_code" -ne 0 ] \
    && grep -Fq 'reason=benchmark_sample_oracle_mismatch index=1' \
        "$TMP/sync-sample.stderr" \
    && [ ! -s "$ARTIFACTS/sync-sample-drift/bench/samples.jsonl" ]; then
    ok 'warmup=0 时 sample 仍固定到 correctness oracle'
else
    bad "benchmark sample drift (prepare=$sync_sample_prepare_code bench=$sync_sample_code)"
    echo "$sync_sample_prepare"
    cat "$TMP/sync-sample.stdout"
    cat "$TMP/sync-sample.stderr"
fi

FAKE_STALE_BWRAP="$TMP/fake-stale-bwrap"
STALE_BWRAP_COUNT="$SUITE_ROOT/stale-bwrap-count"
cat >"$FAKE_STALE_BWRAP" <<'EOF'
#!/usr/bin/env bash
count=$(cat "$FAKE_BWRAP_COUNT" 2>/dev/null || echo 0)
count=$((count + 1))
printf '%s\n' "$count" >"$FAKE_BWRAP_COUNT"
if [ "$count" -gt 4 ]; then
    exit 0
fi
while [ "$#" -gt 0 ]; do
    if [ "$1" = /usr/bin/env ]; then
        exec "$@"
    fi
    shift
done
exit 91
EOF
chmod +x "$FAKE_STALE_BWRAP"
rm -f "$STALE_BWRAP_COUNT"
env PROJECT_SUITE_ROOT="$SUITE_ROOT" PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" \
    MIRVM="$FAKE_GREEN" BWRAP="$FAKE_STALE_BWRAP" \
    FAKE_BWRAP_COUNT="$STALE_BWRAP_COUNT" \
    bash tests/real_projects.sh bench "$BENCH_CASE" \
    >"$TMP/stale-bench.stdout" 2>"$TMP/stale-bench.stderr"
stale_bench_code=$?
stale_samples="$ARTIFACTS/bench-green/bench/samples.jsonl"
if [ "$stale_bench_code" -ne 0 ] \
    && [ ! -s "$TMP/stale-bench.stdout" ] \
    && grep -Fq \
        'reason=benchmark_runner_infrastructure_failed side=native phase=sample index=1' \
        "$TMP/stale-bench.stderr" \
    && [ ! -s "$stale_samples" ]; then
    ok 'benchmark 隔离器失败不能复用旧样本'
else
    bad "benchmark stale sample (exit=$stale_bench_code)"
    echo "--- stdout ---"
    cat "$TMP/stale-bench.stdout"
    echo "--- stderr ---"
    cat "$TMP/stale-bench.stderr"
    test -e "$stale_samples" && cat "$stale_samples"
fi

env PROJECT_SUITE_ROOT="$SUITE_ROOT" PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" \
    MIRVM="$FAKE_XFAIL" \
    bash tests/real_projects.sh bench "$XFAIL_CASE" \
    >"$TMP/xfail-bench.stdout" 2>"$TMP/xfail-bench.stderr"
xfail_bench_code=$?
xfail_bench_samples="$ARTIFACTS/known-red/bench/samples.jsonl"
if [ "$xfail_bench_code" -ne 0 ] \
    && [ ! -s "$TMP/xfail-bench.stdout" ] \
    && grep -Fq 'XFAIL known-red reason=mirvm trap: known.frontier' "$TMP/xfail-bench.stderr" \
    && grep -Fq 'reason=expected_red_not_benchmarkable' "$TMP/xfail-bench.stderr" \
    && [ ! -s "$xfail_bench_samples" ]; then
    ok 'XFAIL 不具备 benchmark 准入资格'
else
    bad "XFAIL benchmark eligibility (exit=$xfail_bench_code)"
    echo "--- stdout ---"
    cat "$TMP/xfail-bench.stdout"
    echo "--- stderr ---"
    cat "$TMP/xfail-bench.stderr"
fi

PORT_FILE="$TMP/listener.port"
NETWORK_MARKER="$TMP/network-reached"
"$PYTHON" - "$PORT_FILE" "$NETWORK_MARKER" <<'PY' &
import pathlib
import socket
import sys

port_file, marker = map(pathlib.Path, sys.argv[1:])
with socket.socket() as listener:
    listener.bind(("127.0.0.1", 0))
    listener.listen(1)
    port_file.write_text(str(listener.getsockname()[1]))
    listener.settimeout(30)
    try:
        connection, _ = listener.accept()
    except TimeoutError:
        pass
    else:
        connection.close()
        marker.write_text("network namespace leaked\n")
PY
SERVER_PID=$!
for _ in $(seq 1 100); do
    [ -s "$PORT_FILE" ] && break
    sleep 0.01
done
PORT=$(cat "$PORT_FILE")

OFFLINE_UPSTREAM="$TMP/offline-upstream"
mkdir -p "$OFFLINE_UPSTREAM/src"
cat >"$OFFLINE_UPSTREAM/Cargo.toml" <<'EOF'
[package]
name = "project-suite-offline"
version = "0.1.0"
edition = "2024"
build = "build.rs"
EOF
cat >"$OFFLINE_UPSTREAM/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "project-suite-offline"
version = "0.1.0"
EOF
cat >"$OFFLINE_UPSTREAM/build.rs" <<EOF
fn main() {
    let checking_offline = std::env::var("CARGO_NET_OFFLINE").as_deref() == Ok("true");
    if checking_offline && std::net::TcpStream::connect(("127.0.0.1", $PORT)).is_ok() {
        panic!("project-suite check leaked network access");
    }
}
EOF
cp "$UPSTREAM/src/main.rs" "$OFFLINE_UPSTREAM/src/main.rs"
git -C "$OFFLINE_UPSTREAM" init -q -b main
git -C "$OFFLINE_UPSTREAM" config user.name 'mirvm test'
git -C "$OFFLINE_UPSTREAM" config user.email 'mirvm-test@example.invalid'
git -C "$OFFLINE_UPSTREAM" add Cargo.toml Cargo.lock build.rs src/main.rs
git -C "$OFFLINE_UPSTREAM" commit -q -m offline-fixture
OFFLINE_REV=$(git -C "$OFFLINE_UPSTREAM" rev-parse HEAD)
OFFLINE_LOCK_SHA256=$(sha256sum "$OFFLINE_UPSTREAM/Cargo.lock" | cut -d' ' -f1)
OFFLINE_CASE="$TMP/offline.toml"
cat >"$OFFLINE_CASE" <<EOF
name = "offline"
repo = "$OFFLINE_UPSTREAM"
rev = "$OFFLINE_REV"
lock_sha256 = "$OFFLINE_LOCK_SHA256"
EOF
offline_prepare=$(env "${common_env[@]}" bash tests/real_projects.sh \
    prepare "$OFFLINE_CASE" 2>&1)
offline_prepare_code=$?
offline_out=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_GREEN" \
    bash tests/real_projects.sh check "$OFFLINE_CASE" 2>&1)
offline_code=$?
kill "$SERVER_PID" 2>/dev/null || true
wait "$SERVER_PID" 2>/dev/null || true
SERVER_PID=
if [ "$offline_prepare_code" -eq 0 ] && [ "$offline_code" -eq 0 ] \
    && echo "$offline_out" | grep -Fq 'PASS offline correctness' \
    && [ ! -e "$NETWORK_MARKER" ]; then
    ok 'check 在断网命名空间中运行'
else
    bad "offline sandbox (prepare=$offline_prepare_code check=$offline_code)"
    echo "$offline_prepare"
    echo "$offline_out"
    test -e "$NETWORK_MARKER" && cat "$NETWORK_MARKER"
fi

PROTECTED_PATH="$SUITE_ROOT/protected/marker"
mkdir -p "$(dirname "$PROTECTED_PATH")"
printf 'original\n' >"$PROTECTED_PATH"
FAKE_PROTECT_CARGO="$TMP/fake-protect-cargo"
FAKE_PROTECT_MIRVM="$TMP/fake-protect-mirvm"
cat >"$FAKE_PROTECT_CARGO" <<'EOF'
#!/usr/bin/env bash
case "${1:-}" in
    fetch|build) exit 0 ;;
    run)
        (printf 'corrupt\n' >"$PROTECTED_PATH") 2>/dev/null || true
        printf 'same-A\n'
        ;;
    *) exit 2 ;;
esac
EOF
cat >"$FAKE_PROTECT_MIRVM" <<'EOF'
#!/usr/bin/env bash
(printf 'corrupt\n' >"$PROTECTED_PATH") 2>/dev/null || true
printf 'same-A\n'
EOF
chmod +x "$FAKE_PROTECT_CARGO" "$FAKE_PROTECT_MIRVM"
PROTECTED_CASE="$TMP/protected-suite.toml"
cat >"$PROTECTED_CASE" <<EOF
name = "protected-suite"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"

[env]
PROTECTED_PATH = "$PROTECTED_PATH"
EOF
protected_prepare=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" CARGO="$FAKE_PROTECT_CARGO" \
    MIRVM="$FAKE_PROTECT_MIRVM" \
    bash tests/real_projects.sh prepare "$PROTECTED_CASE" 2>&1)
protected_prepare_code=$?
printf 'original\n' >"$PROTECTED_PATH"
protected_check=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" CARGO="$FAKE_PROTECT_CARGO" \
    MIRVM="$FAKE_PROTECT_MIRVM" \
    bash tests/real_projects.sh check "$PROTECTED_CASE" 2>&1)
protected_check_code=$?
if [ "$protected_prepare_code" -eq 0 ] && [ "$protected_check_code" -eq 0 ] \
    && echo "$protected_check" | grep -Fq 'PASS protected-suite correctness' \
    && printf 'original\n' | cmp -s - "$PROTECTED_PATH"; then
    ok 'guest 不能写共享 project-suite 状态'
else
    bad "project-suite write isolation (prepare=$protected_prepare_code check=$protected_check_code)"
    echo "$protected_prepare"
    echo "$protected_check"
    cat "$PROTECTED_PATH"
fi

FAKE_RUNTIME_CACHE_CARGO="$TMP/fake-runtime-cache-cargo"
FAKE_RUNTIME_CACHE_MIRVM="$TMP/fake-runtime-cache-mirvm"
cat >"$FAKE_RUNTIME_CACHE_CARGO" <<'EOF'
#!/usr/bin/env bash
case "${1:-}" in
    fetch|build) exit 0 ;;
    run)
        mkdir -p "$XDG_CACHE_HOME/workload"
        printf 'native\n' >"$XDG_CACHE_HOME/workload/created"
        printf 'same-A\n'
        ;;
    *) exit 2 ;;
esac
EOF
cat >"$FAKE_RUNTIME_CACHE_MIRVM" <<'EOF'
#!/usr/bin/env bash
mkdir -p "$XDG_CACHE_HOME/workload"
printf 'mirvm\n' >"$XDG_CACHE_HOME/workload/created"
printf 'same-A\n'
EOF
chmod +x "$FAKE_RUNTIME_CACHE_CARGO" "$FAKE_RUNTIME_CACHE_MIRVM"
RUNTIME_CACHE_CASE="$TMP/runtime-cache.toml"
cat >"$RUNTIME_CACHE_CASE" <<EOF
name = "private-runtime-cache"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
EOF
runtime_cache_prepare=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" CARGO="$FAKE_RUNTIME_CACHE_CARGO" \
    MIRVM="$FAKE_RUNTIME_CACHE_MIRVM" \
    bash tests/real_projects.sh prepare "$RUNTIME_CACHE_CASE" 2>&1)
runtime_cache_prepare_code=$?
runtime_cache_check=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" CARGO="$FAKE_RUNTIME_CACHE_CARGO" \
    MIRVM="$FAKE_RUNTIME_CACHE_MIRVM" \
    bash tests/real_projects.sh check "$RUNTIME_CACHE_CASE" 2>&1)
runtime_cache_check_code=$?
if [ "$runtime_cache_prepare_code" -eq 0 ] && [ "$runtime_cache_check_code" -eq 0 ] \
    && echo "$runtime_cache_check" | grep -Fq \
        'PASS private-runtime-cache correctness'; then
    ok 'native 与 mirvm 各自使用可写的私有 runtime cache'
else
    bad "private runtime cache (prepare=$runtime_cache_prepare_code check=$runtime_cache_check_code)"
    echo "$runtime_cache_prepare"
    echo "$runtime_cache_check"
fi

CWD_UPSTREAM="$TMP/cwd-upstream"
mkdir -p "$CWD_UPSTREAM/src"
cat >"$CWD_UPSTREAM/Cargo.toml" <<'EOF'
[package]
name = "project-suite-cwd"
version = "0.1.0"
edition = "2024"
EOF
cat >"$CWD_UPSTREAM/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "project-suite-cwd"
version = "0.1.0"
EOF
cat >"$CWD_UPSTREAM/src/main.rs" <<'EOF'
fn main() {
    print!("{}", std::fs::read_to_string("fixture.txt").unwrap());
}
EOF
printf 'cwd-ok\n' >"$CWD_UPSTREAM/fixture.txt"
git -C "$CWD_UPSTREAM" init -q -b main
git -C "$CWD_UPSTREAM" config user.name 'mirvm test'
git -C "$CWD_UPSTREAM" config user.email 'mirvm-test@example.invalid'
git -C "$CWD_UPSTREAM" add Cargo.toml Cargo.lock fixture.txt src/main.rs
git -C "$CWD_UPSTREAM" commit -q -m cwd-fixture
CWD_REV=$(git -C "$CWD_UPSTREAM" rev-parse HEAD)
CWD_LOCK_SHA256=$(sha256sum "$CWD_UPSTREAM/Cargo.lock" | cut -d' ' -f1)
CWD_CASE="$TMP/cwd.toml"
cat >"$CWD_CASE" <<EOF
name = "logical-cwd"
repo = "$CWD_UPSTREAM"
rev = "$CWD_REV"
lock_sha256 = "$CWD_LOCK_SHA256"
EOF
FAKE_CWD_MIRVM="$TMP/fake-cwd-mirvm"
cat >"$FAKE_CWD_MIRVM" <<'EOF'
#!/usr/bin/env bash
cat fixture.txt
EOF
chmod +x "$FAKE_CWD_MIRVM"
cwd_prepare=$(env "${common_env[@]}" bash tests/real_projects.sh \
    prepare "$CWD_CASE" 2>&1)
cwd_prepare_code=$?
cwd_out=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_CWD_MIRVM" \
    bash tests/real_projects.sh check "$CWD_CASE" 2>&1)
cwd_code=$?
if [ "$cwd_prepare_code" -eq 0 ] && [ "$cwd_code" -eq 0 ] \
    && echo "$cwd_out" | grep -Fq 'PASS logical-cwd correctness'; then
    ok 'native 与 mirvm 使用相同逻辑 cwd'
else
    bad "logical cwd (prepare=$cwd_prepare_code check=$cwd_code)"
    echo "$cwd_prepare"
    echo "$cwd_out"
fi

FAKE_STDIN_CARGO="$TMP/fake-stdin-cargo"
FAKE_STDIN_MIRVM="$TMP/fake-stdin-mirvm"
cat >"$FAKE_STDIN_CARGO" <<'EOF'
#!/usr/bin/env bash
case "${1:-}" in
    fetch|build) exit 0 ;;
    run)
        if IFS= read -r value; then
            printf 'stdin:%s\n' "$value"
        else
            printf 'stdin:eof\n'
        fi
        ;;
    *) exit 2 ;;
esac
EOF
cat >"$FAKE_STDIN_MIRVM" <<'EOF'
#!/usr/bin/env bash
if IFS= read -r value; then
    printf 'stdin:%s\n' "$value"
else
    printf 'stdin:eof\n'
fi
EOF
chmod +x "$FAKE_STDIN_CARGO" "$FAKE_STDIN_MIRVM"
STDIN_CASE="$TMP/stdin.toml"
cat >"$STDIN_CASE" <<EOF
name = "deterministic-stdin"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
EOF
stdin_prepare=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" CARGO="$FAKE_STDIN_CARGO" \
    MIRVM="$FAKE_STDIN_MIRVM" \
    bash tests/real_projects.sh prepare "$STDIN_CASE" 2>&1)
stdin_prepare_code=$?
stdin_check=$(printf 'ambient input\n' | env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" CARGO="$FAKE_STDIN_CARGO" \
    MIRVM="$FAKE_STDIN_MIRVM" \
    bash tests/real_projects.sh check "$STDIN_CASE" 2>&1)
stdin_check_code=$?
if [ "$stdin_prepare_code" -eq 0 ] && [ "$stdin_check_code" -eq 0 ] \
    && echo "$stdin_check" | grep -Fq 'PASS deterministic-stdin correctness' \
    && printf 'stdin:eof\n' | cmp -s - \
        "$ARTIFACTS/deterministic-stdin/check/native.stdout"; then
    ok '未声明 stdin 时两侧固定使用 EOF'
else
    bad "deterministic stdin (prepare=$stdin_prepare_code check=$stdin_check_code)"
    echo "$stdin_prepare"
    echo "$stdin_check"
    test -e "$ARTIFACTS/deterministic-stdin/check/native.stdout" \
        && cat "$ARTIFACTS/deterministic-stdin/check/native.stdout"
    test -e "$ARTIFACTS/deterministic-stdin/check/mirvm.stdout" \
        && cat "$ARTIFACTS/deterministic-stdin/check/mirvm.stdout"
fi

PREPARE_ISOLATION_UPSTREAM="$TMP/prepare-isolation-upstream"
PREPARE_PROTECTED_PATH="$TMP/prepare-host-protected"
PREPARE_CACHE_POISON="$SUITE_ROOT/cargo-home/build-script-poison"
mkdir -p "$PREPARE_ISOLATION_UPSTREAM/src"
cat >"$PREPARE_ISOLATION_UPSTREAM/Cargo.toml" <<'EOF'
[package]
name = "project-suite-prepare-isolation"
version = "0.1.0"
edition = "2024"
build = "build.rs"
EOF
cat >"$PREPARE_ISOLATION_UPSTREAM/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "project-suite-prepare-isolation"
version = "0.1.0"
EOF
cat >"$PREPARE_ISOLATION_UPSTREAM/build.rs" <<'EOF'
fn main() {
    if let Ok(path) = std::env::var("PREPARE_PROTECTED_PATH") {
        let _ = std::fs::write(path, "corrupt\n");
    }
    if let Ok(path) = std::env::var("PREPARE_CACHE_POISON") {
        let _ = std::fs::write(path, "poisoned\n");
    }
}
EOF
cp "$UPSTREAM/src/main.rs" "$PREPARE_ISOLATION_UPSTREAM/src/main.rs"
git -C "$PREPARE_ISOLATION_UPSTREAM" init -q -b main
git -C "$PREPARE_ISOLATION_UPSTREAM" config user.name 'mirvm test'
git -C "$PREPARE_ISOLATION_UPSTREAM" config user.email 'mirvm-test@example.invalid'
git -C "$PREPARE_ISOLATION_UPSTREAM" add Cargo.toml Cargo.lock build.rs src/main.rs
git -C "$PREPARE_ISOLATION_UPSTREAM" commit -q -m prepare-isolation-fixture
PREPARE_ISOLATION_REV=$(git -C "$PREPARE_ISOLATION_UPSTREAM" rev-parse HEAD)
PREPARE_ISOLATION_LOCK=$(sha256sum "$PREPARE_ISOLATION_UPSTREAM/Cargo.lock" | cut -d' ' -f1)
PREPARE_ISOLATION_CASE="$TMP/prepare-isolation.toml"
cat >"$PREPARE_ISOLATION_CASE" <<EOF
name = "prepare-write-isolation"
repo = "$PREPARE_ISOLATION_UPSTREAM"
rev = "$PREPARE_ISOLATION_REV"
lock_sha256 = "$PREPARE_ISOLATION_LOCK"

[env]
PREPARE_PROTECTED_PATH = "$PREPARE_PROTECTED_PATH"
PREPARE_CACHE_POISON = "$PREPARE_CACHE_POISON"
EOF
printf 'original\n' >"$PREPARE_PROTECTED_PATH"
rm -f "$PREPARE_CACHE_POISON"
prepare_isolation_out=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_GREEN" \
    bash tests/real_projects.sh prepare "$PREPARE_ISOLATION_CASE" 2>&1)
prepare_isolation_code=$?
if [ "$prepare_isolation_code" -eq 0 ] \
    && printf 'original\n' | cmp -s - "$PREPARE_PROTECTED_PATH" \
    && [ ! -e "$PREPARE_CACHE_POISON" ]; then
    ok 'prepare build.rs 不能写宿主工作区或共享 Cargo cache'
else
    bad "prepare build isolation (exit=$prepare_isolation_code)"
    echo "$prepare_isolation_out"
    cat "$PREPARE_PROTECTED_PATH"
    test -e "$PREPARE_CACHE_POISON" && cat "$PREPARE_CACHE_POISON"
fi

FAKE_FETCH_CARGO="$TMP/fake-fetch-cargo"
cat >"$FAKE_FETCH_CARGO" <<'EOF'
#!/usr/bin/env bash
host=$($RUSTC -vV | sed -n 's/^host: //p')
[[ "$*" == *"--locked --target $host"* ]] || exit 90
EOF
chmod +x "$FAKE_FETCH_CARGO"
TARGET_CASE="$TMP/target-fetch.toml"
cat >"$TARGET_CASE" <<EOF
name = "target-fetch"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
EOF
target_prepare=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_GREEN" \
    CARGO="$FAKE_FETCH_CARGO" \
    bash tests/real_projects.sh prepare "$TARGET_CASE" 2>&1)
target_prepare_code=$?
if [ "$target_prepare_code" -eq 0 ]; then
    ok 'prepare 只构建当前 host 的运行依赖图'
else
    bad "target-scoped cargo prepare (exit=$target_prepare_code)"
    echo "$target_prepare"
fi

TARGET_OVERRIDE_UPSTREAM="$TMP/target-override-upstream"
mkdir -p "$TARGET_OVERRIDE_UPSTREAM/src" "$TARGET_OVERRIDE_UPSTREAM/.cargo"
cp "$UPSTREAM/Cargo.toml" "$UPSTREAM/Cargo.lock" "$TARGET_OVERRIDE_UPSTREAM/"
cp "$UPSTREAM/src/main.rs" "$TARGET_OVERRIDE_UPSTREAM/src/main.rs"
cat >"$TARGET_OVERRIDE_UPSTREAM/.cargo/config.toml" <<'EOF'
[build]
target = "project-suite-invalid-target"
EOF
git -C "$TARGET_OVERRIDE_UPSTREAM" init -q -b main
git -C "$TARGET_OVERRIDE_UPSTREAM" config user.name 'mirvm test'
git -C "$TARGET_OVERRIDE_UPSTREAM" config user.email 'mirvm-test@example.invalid'
git -C "$TARGET_OVERRIDE_UPSTREAM" add Cargo.toml Cargo.lock .cargo/config.toml src/main.rs
git -C "$TARGET_OVERRIDE_UPSTREAM" commit -q -m target-override-fixture
TARGET_OVERRIDE_REV=$(git -C "$TARGET_OVERRIDE_UPSTREAM" rev-parse HEAD)
TARGET_OVERRIDE_LOCK=$(sha256sum "$TARGET_OVERRIDE_UPSTREAM/Cargo.lock" | cut -d' ' -f1)
TARGET_OVERRIDE_CASE="$TMP/target-override.toml"
cat >"$TARGET_OVERRIDE_CASE" <<EOF
name = "explicit-host-target"
repo = "$TARGET_OVERRIDE_UPSTREAM"
rev = "$TARGET_OVERRIDE_REV"
lock_sha256 = "$TARGET_OVERRIDE_LOCK"

[bench]
warmup = 1
samples = 1
EOF
target_override_prepare=$(env "${common_env[@]}" bash tests/real_projects.sh \
    prepare "$TARGET_OVERRIDE_CASE" 2>&1)
target_override_prepare_code=$?
target_override_check=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_GREEN" \
    bash tests/real_projects.sh check "$TARGET_OVERRIDE_CASE" 2>&1)
target_override_check_code=$?
if [ "$target_override_prepare_code" -eq 0 ] \
    && [ "$target_override_check_code" -eq 0 ] \
    && echo "$target_override_check" | grep -Fq \
        'PASS explicit-host-target correctness'; then
    ok 'correctness 显式固定 native host target'
else
    bad "correctness host target (prepare=$target_override_prepare_code check=$target_override_check_code)"
    echo "$target_override_prepare"
    echo "$target_override_check"
fi
env PROJECT_SUITE_ROOT="$SUITE_ROOT" PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" \
    MIRVM="$FAKE_GREEN" bash tests/real_projects.sh bench "$TARGET_OVERRIDE_CASE" \
    >"$TMP/target-override-bench.stdout" 2>"$TMP/target-override-bench.stderr"
target_override_bench_code=$?
target_override_samples="$ARTIFACTS/explicit-host-target/bench/samples.jsonl"
if [ "$target_override_bench_code" -eq 0 ] \
    && [ "$(wc -l <"$target_override_samples" 2>/dev/null || echo 0)" -eq 1 ]; then
    ok 'benchmark 显式固定 native host target'
else
    bad "benchmark host target (exit=$target_override_bench_code)"
    cat "$TMP/target-override-bench.stdout"
    cat "$TMP/target-override-bench.stderr"
    test -e "$target_override_samples" && cat "$target_override_samples"
fi

PERSISTENT_CACHE="$SUITE_ROOT/persistent-mirvm-xdg"
mkdir -p "$PERSISTENT_CACHE/mirvm"
printf 'ready\n' >"$PERSISTENT_CACHE/mirvm/prepared.marker"
PERSISTENT_SYSROOT_MARKER="$PERSISTENT_CACHE/mirvm/sysroot-$HOST_TARGET/lib/rustlib/$HOST_TARGET/.rustc-build-sysroot-hash"
mkdir -p "$(dirname "$PERSISTENT_SYSROOT_MARKER")"
printf 'test sysroot\n' >"$PERSISTENT_SYSROOT_MARKER"
FAKE_CACHE_MIRVM="$TMP/fake-cache-mirvm"
cat >"$FAKE_CACHE_MIRVM" <<'EOF'
#!/usr/bin/env bash
if [ ! -f "$XDG_CACHE_HOME/mirvm/prepared.marker" ]; then
    echo 'prepared mirvm cache not visible' >&2
    exit 71
fi
printf 'same-A\n'
EOF
chmod +x "$FAKE_CACHE_MIRVM"
CACHE_CASE="$TMP/persistent-cache.toml"
cat >"$CACHE_CASE" <<EOF
name = "persistent-cache"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
EOF
cache_prepare=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" \
    PROJECT_SUITE_MIRVM_CACHE="$PERSISTENT_CACHE" MIRVM="$FAKE_CACHE_MIRVM" \
    bash tests/real_projects.sh prepare "$CACHE_CASE" 2>&1)
cache_prepare_code=$?
cache_out=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" \
    PROJECT_SUITE_MIRVM_CACHE="$PERSISTENT_CACHE" MIRVM="$FAKE_CACHE_MIRVM" \
    bash tests/real_projects.sh check "$CACHE_CASE" 2>&1)
cache_code=$?
if [ "$cache_prepare_code" -eq 0 ] && [ "$cache_code" -eq 0 ] \
    && echo "$cache_out" | grep -Fq 'PASS persistent-cache correctness'; then
    ok 'mirvm 使用持久的已准备 XDG cache'
else
    bad "persistent mirvm cache (prepare=$cache_prepare_code check=$cache_code)"
    echo "$cache_prepare"
    echo "$cache_out"
fi

PREPARED_CACHE="$SUITE_ROOT/prepare-owned-mirvm-xdg"
PREPARED_MARKER="$PREPARED_CACHE/mirvm/sysroot-$HOST_TARGET/lib/rustlib/$HOST_TARGET/.rustc-build-sysroot-hash"
FAKE_PREPARE_MIRVM="$TMP/fake-prepare-mirvm"
cat >"$FAKE_PREPARE_MIRVM" <<'EOF'
#!/usr/bin/env bash
host=$($RUSTC -vV | sed -n 's/^host: //p')
if [[ "${2:-}" == *.rs ]]; then
    marker="$XDG_CACHE_HOME/mirvm/sysroot-$host/lib/rustlib/$host/.rustc-build-sysroot-hash"
    mkdir -p "$(dirname "$marker")"
    printf 'prepared by fake mirvm\n' >"$marker"
    exit 0
fi
if [ ! -f "$XDG_CACHE_HOME/mirvm/sysroot-$host/lib/rustlib/$host/.rustc-build-sysroot-hash" ]; then
    echo 'prepare did not provision mirvm sysroot' >&2
    exit 71
fi
printf 'same-A\n'
EOF
chmod +x "$FAKE_PREPARE_MIRVM"
PREPARE_CACHE_CASE="$TMP/prepare-cache.toml"
cat >"$PREPARE_CACHE_CASE" <<EOF
name = "prepare-cache"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
EOF
prepare_cache_out=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" \
    PROJECT_SUITE_MIRVM_CACHE="$PREPARED_CACHE" MIRVM="$FAKE_PREPARE_MIRVM" \
    bash tests/real_projects.sh prepare "$PREPARE_CACHE_CASE" 2>&1)
prepare_cache_code=$?
prepared_check_out=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" \
    PROJECT_SUITE_MIRVM_CACHE="$PREPARED_CACHE" MIRVM="$FAKE_PREPARE_MIRVM" \
    bash tests/real_projects.sh check "$PREPARE_CACHE_CASE" 2>&1)
prepared_check_code=$?
if [ "$prepare_cache_code" -eq 0 ] && [ -s "$PREPARED_MARKER" ] \
    && [ "$prepared_check_code" -eq 0 ] \
    && echo "$prepared_check_out" | grep -Fq 'PASS prepare-cache correctness'; then
    ok 'prepare 建立持久 mirvm sysroot cache'
else
    bad "prepare mirvm cache (prepare=$prepare_cache_code check=$prepared_check_code)"
    echo "$prepare_cache_out"
    echo "$prepared_check_out"
fi

FAKE_DRIFT="$TMP/fake-drift-mirvm"
cat >"$FAKE_DRIFT" <<'EOF'
#!/usr/bin/env bash
echo 'mirvm trap: different.frontier' >&2
exit 70
EOF
chmod +x "$FAKE_DRIFT"
drift_out=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_DRIFT" \
    bash tests/real_projects.sh check "$XFAIL_CASE" 2>&1)
drift_code=$?
if [ "$drift_code" -ne 0 ] \
    && echo "$drift_out" | grep -Fq \
        'FAIL known-red reason=xfail_diagnostic_mismatch expected=mirvm trap: known.frontier'; then
    ok 'expected-red 诊断漂移会失败'
else
    bad "XFAIL diagnostic drift (exit=$drift_code)"
    echo "$drift_out"
fi

FAKE_CONTEXT_DRIFT="$TMP/fake-context-drift-mirvm"
cat >"$FAKE_CONTEXT_DRIFT" <<'EOF'
#!/usr/bin/env bash
echo 'mirvm trap: known.frontier' >&2
echo 'mirvm trap: new.primary.frontier' >&2
exit 70
EOF
chmod +x "$FAKE_CONTEXT_DRIFT"
context_drift_out=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_CONTEXT_DRIFT" \
    bash tests/real_projects.sh check "$XFAIL_CASE" 2>&1)
context_drift_code=$?
if [ "$context_drift_code" -ne 0 ] \
    && echo "$context_drift_out" | grep -Fq 'reason=xfail_diagnostic_mismatch'; then
    ok '旧诊断只作上下文时不能命中 XFAIL'
else
    bad "XFAIL contextual diagnostic (exit=$context_drift_code)"
    echo "$context_drift_out"
fi

FAKE_REVERSE_CONTEXT="$TMP/fake-reverse-context-mirvm"
cat >"$FAKE_REVERSE_CONTEXT" <<'EOF'
#!/usr/bin/env bash
echo 'mirvm trap: new.primary.frontier' >&2
echo 'mirvm trap: known.frontier' >&2
exit 70
EOF
chmod +x "$FAKE_REVERSE_CONTEXT"
reverse_context_out=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_REVERSE_CONTEXT" \
    bash tests/real_projects.sh check "$XFAIL_CASE" 2>&1)
reverse_context_code=$?
if [ "$reverse_context_code" -ne 0 ] \
    && echo "$reverse_context_out" | grep -Fq 'reason=xfail_diagnostic_mismatch'; then
    ok '旧诊断位于末行也不能遮住新主故障'
else
    bad "XFAIL reverse contextual diagnostic (exit=$reverse_context_code)"
    echo "$reverse_context_out"
fi

FAKE_CARGO_TRAILER="$TMP/fake-cargo-trailer-mirvm"
cat >"$FAKE_CARGO_TRAILER" <<'EOF'
#!/usr/bin/env bash
echo 'mirvm trap: known.frontier' >&2
echo "error: process didn't exit successfully: mirvm runner (exit status: 70)" >&2
exit 70
EOF
chmod +x "$FAKE_CARGO_TRAILER"
cargo_trailer_out=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_CARGO_TRAILER" \
    bash tests/real_projects.sh check "$XFAIL_CASE" 2>&1)
cargo_trailer_code=$?
if [ "$cargo_trailer_code" -eq 0 ] \
    && echo "$cargo_trailer_out" | grep -Fq \
        'XFAIL known-red reason=mirvm trap: known.frontier'; then
    ok 'canonical XFAIL 允许非 mirvm Cargo trailer'
else
    bad "XFAIL Cargo trailer (exit=$cargo_trailer_code)"
    echo "$cargo_trailer_out"
fi

MUTATE_UPSTREAM="$TMP/mutate-upstream"
mkdir -p "$MUTATE_UPSTREAM/src"
cat >"$MUTATE_UPSTREAM/Cargo.toml" <<'EOF'
[package]
name = "project-suite-mutate"
version = "0.1.0"
edition = "2024"
EOF
cat >"$MUTATE_UPSTREAM/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "project-suite-mutate"
version = "0.1.0"
EOF
cat >"$MUTATE_UPSTREAM/src/main.rs" <<'EOF'
fn main() {
    std::fs::write("tracked.txt", "mutated\n").unwrap();
    println!("same-A");
}
EOF
printf 'original\n' >"$MUTATE_UPSTREAM/tracked.txt"
git -C "$MUTATE_UPSTREAM" init -q -b main
git -C "$MUTATE_UPSTREAM" config user.name 'mirvm test'
git -C "$MUTATE_UPSTREAM" config user.email 'mirvm-test@example.invalid'
git -C "$MUTATE_UPSTREAM" add Cargo.toml Cargo.lock tracked.txt src/main.rs
git -C "$MUTATE_UPSTREAM" commit -q -m mutate-fixture
MUTATE_REV=$(git -C "$MUTATE_UPSTREAM" rev-parse HEAD)
MUTATE_LOCK_SHA256=$(sha256sum "$MUTATE_UPSTREAM/Cargo.lock" | cut -d' ' -f1)
MUTATE_CASE="$TMP/mutate.toml"
cat >"$MUTATE_CASE" <<EOF
name = "tracked-mutation"
repo = "$MUTATE_UPSTREAM"
rev = "$MUTATE_REV"
lock_sha256 = "$MUTATE_LOCK_SHA256"
EOF
FAKE_MUTATE_MIRVM="$TMP/fake-mutate-mirvm"
cat >"$FAKE_MUTATE_MIRVM" <<'EOF'
#!/usr/bin/env bash
printf 'mutated\n' >tracked.txt
printf 'same-A\n'
EOF
chmod +x "$FAKE_MUTATE_MIRVM"
mutate_prepare=$(env "${common_env[@]}" bash tests/real_projects.sh \
    prepare "$MUTATE_CASE" 2>&1)
mutate_prepare_code=$?
mutate_out=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_MUTATE_MIRVM" \
    bash tests/real_projects.sh check "$MUTATE_CASE" 2>&1)
mutate_code=$?
if [ "$mutate_prepare_code" -eq 0 ] && [ "$mutate_code" -ne 0 ] \
    && echo "$mutate_out" | grep -Fq \
        'FAIL tracked-mutation reason=source_tree_mutated side=native'; then
    ok '运行后拒绝 tracked source mutation'
else
    bad "tracked source mutation (prepare=$mutate_prepare_code check=$mutate_code)"
    echo "$mutate_prepare"
    echo "$mutate_out"
fi

FAKE_BENCH_MUTATE_CARGO="$TMP/fake-bench-mutate-cargo"
FAKE_BENCH_MUTATE_MIRVM="$TMP/fake-bench-mutate-mirvm"
cat >"$FAKE_BENCH_MUTATE_CARGO" <<'EOF'
#!/usr/bin/env bash
case "${1:-}" in
    fetch|build) exit 0 ;;
    run)
        if [[ "$(pwd)" == *-bench.* ]]; then
            printf '// benchmark mutation\n' >src/main.rs
        fi
        printf 'same-A\n'
        ;;
    *) exit 2 ;;
esac
EOF
cat >"$FAKE_BENCH_MUTATE_MIRVM" <<'EOF'
#!/usr/bin/env bash
if [[ "$(pwd)" == *-bench.* ]]; then
    printf '// benchmark mutation\n' >src/main.rs
fi
printf 'same-A\n'
EOF
chmod +x "$FAKE_BENCH_MUTATE_CARGO" "$FAKE_BENCH_MUTATE_MIRVM"
BENCH_MUTATE_CASE="$TMP/bench-mutation.toml"
cat >"$BENCH_MUTATE_CASE" <<EOF
name = "benchmark-mutation"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"

[bench]
warmup = 1
samples = 1
EOF
bench_mutate_prepare=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" CARGO="$FAKE_BENCH_MUTATE_CARGO" \
    MIRVM="$FAKE_BENCH_MUTATE_MIRVM" \
    bash tests/real_projects.sh prepare "$BENCH_MUTATE_CASE" 2>&1)
bench_mutate_prepare_code=$?
env PROJECT_SUITE_ROOT="$SUITE_ROOT" PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" \
    CARGO="$FAKE_BENCH_MUTATE_CARGO" MIRVM="$FAKE_BENCH_MUTATE_MIRVM" \
    bash tests/real_projects.sh bench "$BENCH_MUTATE_CASE" \
    >"$TMP/bench-mutation.stdout" 2>"$TMP/bench-mutation.stderr"
bench_mutate_code=$?
if [ "$bench_mutate_prepare_code" -eq 0 ] && [ "$bench_mutate_code" -ne 0 ] \
    && [ ! -s "$TMP/bench-mutation.stdout" ] \
    && grep -Fq 'reason=source_tree_mutated side=native' \
        "$TMP/bench-mutation.stderr" \
    && [ ! -s "$ARTIFACTS/benchmark-mutation/bench/samples.jsonl" ]; then
    ok 'benchmark 每轮拒绝 tracked source mutation'
else
    bad "benchmark tracked mutation (prepare=$bench_mutate_prepare_code bench=$bench_mutate_code)"
    echo "$bench_mutate_prepare"
    cat "$TMP/bench-mutation.stdout"
    cat "$TMP/bench-mutation.stderr"
fi

NATIVE_FAIL_MARKER="$SUITE_ROOT/native-fail-called-mirvm"
NATIVE_FAIL_CASE="$TMP/native-fail.toml"
cat >"$NATIVE_FAIL_CASE" <<EOF
name = "native-baseline"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
expected_exit = 7

[env]
NATIVE_FAIL_MARKER = "$NATIVE_FAIL_MARKER"
EOF
FAKE_MUST_NOT_RUN="$TMP/fake-must-not-run"
cat >"$FAKE_MUST_NOT_RUN" <<'EOF'
#!/usr/bin/env bash
echo called >"$NATIVE_FAIL_MARKER"
exit 7
EOF
chmod +x "$FAKE_MUST_NOT_RUN"
native_fail_prepare=$(env "${common_env[@]}" bash tests/real_projects.sh \
    prepare "$NATIVE_FAIL_CASE" 2>&1)
native_fail_prepare_code=$?
native_fail_out=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_MUST_NOT_RUN" \
    NATIVE_FAIL_MARKER="$NATIVE_FAIL_MARKER" \
    bash tests/real_projects.sh check "$NATIVE_FAIL_CASE" 2>&1)
native_fail_code=$?
if [ "$native_fail_prepare_code" -eq 0 ] && [ "$native_fail_code" -ne 0 ] \
    && echo "$native_fail_out" | grep -Fq \
        'FAIL native-baseline native_baseline_failed exit=0 expected=7' \
    && [ ! -e "$NATIVE_FAIL_MARKER" ]; then
    ok 'native baseline 失败时不调用 mirvm'
else
    bad "native baseline oracle (prepare=$native_fail_prepare_code check=$native_fail_code)"
    echo "$native_fail_prepare"
    echo "$native_fail_out"
    test -e "$NATIVE_FAIL_MARKER" && cat "$NATIVE_FAIL_MARKER"
fi

TOOL_DIR="$TMP/toolchain-bin"
mkdir -p "$TOOL_DIR"
PINNED_CARGO="$TOOL_DIR/pinned-cargo"
PINNED_RUSTC="$TOOL_DIR/pinned-rustc"
cat >"$TOOL_DIR/rustup" <<'EOF'
#!/usr/bin/env bash
if [ "$1" = which ] && [ "$2" = cargo ]; then
    echo "$PINNED_CARGO"
elif [ "$1" = which ] && [ "$2" = rustc ]; then
    echo "$PINNED_RUSTC"
else
    exit 2
fi
EOF
cat >"$TOOL_DIR/cargo" <<'EOF'
#!/usr/bin/env bash
exit 88
EOF
cat >"$TOOL_DIR/rustc" <<'EOF'
#!/usr/bin/env bash
if [ "${1:-}" = -vV ]; then
    printf 'rustc proxy\nhost: x86_64-unknown-linux-gnu\n'
else
    exit 88
fi
EOF
cat >"$PINNED_CARGO" <<'EOF'
#!/usr/bin/env bash
"$RUSTC" -vV | grep -Fq 'rustc pinned' || exit 89
case "${1:-}" in
    fetch|build) exit 0 ;;
    run) printf 'same-A\n'; exit 0 ;;
    *) exit 2 ;;
esac
EOF
cat >"$PINNED_RUSTC" <<'EOF'
#!/usr/bin/env bash
if [ "${1:-}" = -vV ]; then
    printf 'rustc pinned\nhost: x86_64-unknown-linux-gnu\n'
else
    exit 2
fi
EOF
chmod +x "$TOOL_DIR/rustup" "$TOOL_DIR/cargo" "$TOOL_DIR/rustc" \
    "$PINNED_CARGO" "$PINNED_RUSTC"
TOOLCHAIN_CASE="$TMP/toolchain.toml"
cat >"$TOOLCHAIN_CASE" <<EOF
name = "pinned-toolchain"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
EOF
toolchain_prepare=$(env -u CARGO -u RUSTC PATH="$TOOL_DIR:$PATH" \
    PROJECT_SUITE_ROOT="$SUITE_ROOT" PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" \
    MIRVM="$FAKE_GREEN" PINNED_CARGO="$PINNED_CARGO" PINNED_RUSTC="$PINNED_RUSTC" \
    bash tests/real_projects.sh prepare "$TOOLCHAIN_CASE" 2>&1)
toolchain_prepare_code=$?
toolchain_out=$(env -u CARGO -u RUSTC PATH="$TOOL_DIR:$PATH" \
    PROJECT_SUITE_ROOT="$SUITE_ROOT" PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" \
    MIRVM="$FAKE_GREEN" PINNED_CARGO="$PINNED_CARGO" PINNED_RUSTC="$PINNED_RUSTC" \
    bash tests/real_projects.sh check "$TOOLCHAIN_CASE" 2>&1)
toolchain_code=$?
if [ "$toolchain_prepare_code" -eq 0 ] && [ "$toolchain_code" -eq 0 ] \
    && echo "$toolchain_out" | grep -Fq 'PASS pinned-toolchain correctness'; then
    ok '启动时冻结 rustup toolchain 二进制路径'
else
    bad "pinned toolchain (prepare=$toolchain_prepare_code check=$toolchain_code)"
    echo "$toolchain_prepare"
    echo "$toolchain_out"
fi

ENV_UPSTREAM="$TMP/env-upstream"
mkdir -p "$ENV_UPSTREAM/src"
cat >"$ENV_UPSTREAM/Cargo.toml" <<'EOF'
[package]
name = "project-suite-env"
version = "0.1.0"
edition = "2024"
EOF
cat >"$ENV_UPSTREAM/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "project-suite-env"
version = "0.1.0"
EOF
cat >"$ENV_UPSTREAM/src/main.rs" <<'EOF'
fn main() {
    println!("{}", std::env::var("AMBIENT_SECRET").unwrap_or_else(|_| "unset".into()));
}
EOF
git -C "$ENV_UPSTREAM" init -q -b main
git -C "$ENV_UPSTREAM" config user.name 'mirvm test'
git -C "$ENV_UPSTREAM" config user.email 'mirvm-test@example.invalid'
git -C "$ENV_UPSTREAM" add Cargo.toml Cargo.lock src/main.rs
git -C "$ENV_UPSTREAM" commit -q -m env-fixture
ENV_REV=$(git -C "$ENV_UPSTREAM" rev-parse HEAD)
ENV_LOCK_SHA256=$(sha256sum "$ENV_UPSTREAM/Cargo.lock" | cut -d' ' -f1)
ENV_CASE="$TMP/environment.toml"
cat >"$ENV_CASE" <<EOF
name = "clean-environment"
repo = "$ENV_UPSTREAM"
rev = "$ENV_REV"
lock_sha256 = "$ENV_LOCK_SHA256"
EOF
FAKE_ENV_MIRVM="$TMP/fake-env-mirvm"
cat >"$FAKE_ENV_MIRVM" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "${AMBIENT_SECRET:-unset}"
EOF
chmod +x "$FAKE_ENV_MIRVM"
env_prepare=$(env AMBIENT_SECRET=leaked PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_ENV_MIRVM" \
    bash tests/real_projects.sh prepare "$ENV_CASE" 2>&1)
env_prepare_code=$?
env_out=$(env AMBIENT_SECRET=leaked PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_ENV_MIRVM" \
    bash tests/real_projects.sh check "$ENV_CASE" 2>&1)
env_code=$?
if [ "$env_prepare_code" -eq 0 ] && [ "$env_code" -eq 0 ] \
    && echo "$env_out" | grep -Fq 'PASS clean-environment correctness' \
    && printf 'unset\n' | cmp -s - "$ARTIFACTS/clean-environment/check/native.stdout"; then
    ok '未声明的 ambient env 不进入 guest'
else
    bad "clean environment (prepare=$env_prepare_code check=$env_code)"
    echo "$env_prepare"
    echo "$env_out"
    test -e "$ARTIFACTS/clean-environment/check/native.stdout" \
        && cat "$ARTIFACTS/clean-environment/check/native.stdout"
fi

PYTHON_POISON="$TMP/python-poison"
mkdir -p "$PYTHON_POISON"
cat >"$PYTHON_POISON/sitecustomize.py" <<'PY'
raise SystemExit("benchmark controller inherited guest PYTHONPATH")
PY
FAKE_GUEST_ENV_CARGO="$TMP/fake-guest-env-cargo"
FAKE_GUEST_ENV_MIRVM="$TMP/fake-guest-env-mirvm"
cat >"$FAKE_GUEST_ENV_CARGO" <<'EOF'
#!/usr/bin/env bash
case "${1:-}" in
    fetch|build) exit 0 ;;
    run) printf '%s\n' "$PYTHONPATH" ;;
    *) exit 2 ;;
esac
EOF
cat >"$FAKE_GUEST_ENV_MIRVM" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$PYTHONPATH"
EOF
chmod +x "$FAKE_GUEST_ENV_CARGO" "$FAKE_GUEST_ENV_MIRVM"
GUEST_ENV_CASE="$TMP/guest-env-only.toml"
cat >"$GUEST_ENV_CASE" <<EOF
name = "guest-env-only"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"

[env]
PYTHONPATH = "$PYTHON_POISON"

[bench]
warmup = 1
samples = 1
EOF
guest_env_prepare=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" CARGO="$FAKE_GUEST_ENV_CARGO" \
    MIRVM="$FAKE_GUEST_ENV_MIRVM" \
    bash tests/real_projects.sh prepare "$GUEST_ENV_CASE" 2>&1)
guest_env_prepare_code=$?
env PROJECT_SUITE_ROOT="$SUITE_ROOT" PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" \
    CARGO="$FAKE_GUEST_ENV_CARGO" MIRVM="$FAKE_GUEST_ENV_MIRVM" \
    bash tests/real_projects.sh bench "$GUEST_ENV_CASE" \
    >"$TMP/guest-env-bench.stdout" 2>"$TMP/guest-env-bench.stderr"
guest_env_bench_code=$?
if [ "$guest_env_prepare_code" -eq 0 ] && [ "$guest_env_bench_code" -eq 0 ] \
    && [ -s "$ARTIFACTS/guest-env-only/bench/summary.json" ]; then
    ok 'case env 只进入 workload、不进入 benchmark controller'
else
    bad "guest-only benchmark env (prepare=$guest_env_prepare_code bench=$guest_env_bench_code)"
    echo "$guest_env_prepare"
    cat "$TMP/guest-env-bench.stdout"
    cat "$TMP/guest-env-bench.stderr"
fi

INFRA_MARKER="$SUITE_ROOT/infra-mirvm-called"
INFRA_CASE="$TMP/infra-exit.toml"
cat >"$INFRA_CASE" <<EOF
name = "infra-exit"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
expected_exit = 1

[env]
INFRA_MIRVM_MARKER = "$INFRA_MARKER"
EOF
FAKE_INFRA_MIRVM="$TMP/fake-infra-mirvm"
cat >"$FAKE_INFRA_MIRVM" <<'EOF'
#!/usr/bin/env bash
echo called >"$INFRA_MIRVM_MARKER"
exit 1
EOF
chmod +x "$FAKE_INFRA_MIRVM"
infra_prepare=$(env "${common_env[@]}" bash tests/real_projects.sh \
    prepare "$INFRA_CASE" 2>&1)
infra_prepare_code=$?
infra_out=$(env PROJECT_SUITE_ROOT="$SUITE_ROOT" \
    PROJECT_SUITE_ARTIFACTS="$ARTIFACTS" MIRVM="$FAKE_INFRA_MIRVM" \
    BWRAP=/bin/false bash tests/real_projects.sh check "$INFRA_CASE" 2>&1)
infra_code=$?
if [ "$infra_prepare_code" -eq 0 ] && [ "$infra_code" -ne 0 ] \
    && echo "$infra_out" | grep -Fq \
        'FAIL infra-exit reason=runner_infrastructure_failed side=native' \
    && [ ! -e "$INFRA_MARKER" ]; then
    ok '隔离器失败不能冒充 guest 退出码'
else
    bad "runner infrastructure status (prepare=$infra_prepare_code check=$infra_code)"
    echo "$infra_prepare"
    echo "$infra_out"
    test -e "$INFRA_MARKER" && cat "$INFRA_MARKER"
fi

RESERVED_EXIT_CASE="$TMP/reserved-exit.toml"
cat >"$RESERVED_EXIT_CASE" <<EOF
name = "reserved-exit"
repo = "$UPSTREAM"
rev = "$REV"
lock_sha256 = "$LOCK_SHA256"
expected_exit = 124
EOF
reserved_out=$(env "${common_env[@]}" bash tests/real_projects.sh \
    prepare "$RESERVED_EXIT_CASE" 2>&1)
reserved_code=$?
if [ "$reserved_code" -ne 0 ] \
    && echo "$reserved_out" | grep -Fq 'invalid_case: expected_exit 124 is reserved by project-suite'; then
    ok 'timeout/runner 退出码不能声明为 guest 结果'
else
    bad "reserved harness exit (exit=$reserved_code)"
    echo "$reserved_out"
fi

echo "---"
echo "real-projects-regression: $pass pass, $fail fail"
[ "$fail" -eq 0 ]
